import re

class FindMotif:
    def __init__(self):
        pass

    def find_t_in_s(self,s,t):
        return [n + 1 for n in range(len(s)) if s.find(t, n) == n]

    def find_motif_in_string(self,inputString,motif):
        return self.find_t_in_s(inputString,motif)

def main():
    fm = FindMotif()
    s = 'GTTAGGCGTTAGGCTGTTAGGCTAGTTAGGCTTGGTTAGGCCAGTTAGGCAAAAAACGGGCGTTAGGCGTTAGGCGGTTAGGCAGACTCACGTTAGGCACAGGGTTAGGCTGATGACCGTTAGGCCGGTTAGGCCAGGTTAGGCGAAAGTTAGGCCGTTAGGCAGTTAGGCCGTTAGGCTAAAGTTAGGCGTTAGGCTAATGGTGTTAGGCCGTGGTTAGGCCTACTGTTAGGCCGAAGGCTAAGTTAGGCGCGAGGTTAGGCTGTTAGGCGTTGCAGTTAGGCTGTTAGGCCTTACAGGTTAGGCCCTCGTTAGGCCAGCTCGTTAGGCCCGTTAGGCGTGTTAGGCTACGGTTAGGCGTTAGGCGTTAGGCCTGCCGTTAGGCGTTAGGCAGTTAGGCACCCTCCCGTTAGGCGGTTAGGCGTTAGGCCAGCGTTAGGCTAGGGGTTAGGCAGTTAGGCGTTAGGCTTTGGTTAGGCAGTTAGGCCGTTAGGCGTTAGGCACAAGTTAGGCCGTTAGGCGGTTTGTTAGGCTGGGGCGTTAGGCGTTAGGCAAAGTTAGGCATCAGATTAGTTAGGCGCGACGAAGAAACAATGTTAGGCGCTGTTAGGCCCGTTAGGCCAGGTTAGGCGTTAGGCGCAGGTTAGGCTTACGTTAGGCAGTGGTTAGGCGTAGTTAGGCCAGTTAGGCTGGCCAATTTGTTAGGCTCGTTAGGCGTTAGGCGCTGGATGAAGTTAGGCCGAGTTAGGCGTTAGGCGTTAGGCGTTAGGCAGTTAGGCGGAAGTTAGGCAGTTAGGCCTGGTTAGGCGTTAGGCCTTGTTAGGCGGTTAGGCAACGTTAGGCAGAGTGAGTTAGGCTGTTAGGCGCGC'
    t = 'GTTAGGCGT'
    print (*fm.find_motif_in_string(s,t))

if __name__ == '__main__':
    main()