#Matt Person
#Rosalind Problem: NWCK
#source
'''Given: A collection of n trees (n≤40) in Newick format, with each tree containing at most 200 nodes;
each tree Tk is followed by a pair of nodes xk and yk in Tk.
Return: A collection of n positive integers, for which the kth integer represents the distance between xk and yk in Tk.'''

#Note: Might go back and use rosalind utilities Newick tree for this...


class NWCK:
    def __init__(self, Tk, xk, yk):
        self.nwck_tree = Tk
        self.edges = {}
        self.GUID = 0
        self.i = 0
        self.load_all_edges()
        self.distance_between_nodes = self.get_distance_between_nodes(xk,yk)

    def load_all_edges(self):
        next_token = self.get_next_token()
        while next_token != ';':
            if next_token == '(':
                self.load_edges()
                next_token = self.get_next_token()

    def get_GUID(self):
        self.GUID += 1
        return self.GUID

    def load_edges(self):
        nodes_at_level = []
        next_token = self.get_next_token()
        while next_token != ')' and next_token != ';':
            if next_token == '(':
                nodes_at_level.append(self.load_edges())
            elif next_token not in '(,':
                nodes_at_level.append(next_token)
            next_token = self.get_next_token()
        next_token = self.get_next_token()
        if self.is_special_character(next_token):
            node = self.get_GUID()
            self.i -= 1
        else:
            node = next_token
        self.add_edges(nodes_at_level,node)
        return node

    def add_edges(self,nodes,root_node):
        for node in nodes:
            self.edges[node] = self.edges.get(node,[]) + [root_node]
            self.edges[root_node] = self.edges.get(root_node, []) + [node]

    def get_distance_between_nodes(self,node_a,node_b):
        #BFS of edges
        queue = [(node_a,0)]
        visited = set()

        while len(queue) > 0:
            node = queue.pop()
            visited.add(node[0])
            if node[0] == node_b:
                return node[1]
            for adjacent_node in self.edges[node[0]]:
                if adjacent_node not in visited:
                    queue.insert(0,(adjacent_node,node[1]+1))
        return -1


    def is_special_character(self,char):
        return char in '(),;'

    def get_next_token(self):
        start_pos = self.i
        if start_pos >= len(self.nwck_tree):
            return ''
        end_pos = start_pos + 1
        if self.is_special_character(self.nwck_tree[start_pos]):
            self.i = end_pos
            return self.nwck_tree[start_pos]
        while not self.is_special_character(self.nwck_tree[end_pos]):
                end_pos +=1
        self.i = end_pos
        return ''.join([self.nwck_tree[i] for i in range(start_pos,end_pos)])


def Main():
    data = '''((((Acanthoscurria_sujfunensis,((((((((((((((((((((((((((((Apalone_piceus,((((((Aplopeltura_valliceps,(Cygnopsis_cinereus,(Otocoris_belliana,Pelodiscus_rudicolis))),Paraphysa_atthis),Cuculus_cristatella),Damon_blakistoni),(Brachypelma_albocinctus,((Osmoderma_apus,Phormictopus_barbatus),Sitta_opimus))),Sus_tinctorius)),Butastur_perdix),Psalmopoeus_indica),Aythya_gratiosa),Casarca_japonensis),Crotaphytus_tricolor),Pyrrhocorax_cynodon),Selenocosmia_albicilla),Siniperca_smaragdina),(Gecarcinus_pallasii,Meles_flavomaculatus)),Glareola_sauromates),Eschrichtius_piceus),Cyclagras_wogura),Buthacus_barbata),Enhydra_rostratus),Rhombomys_krueperi),((Eryx_leucoryphus,(Homalopsis_gemmicincta,Leiolepis_helvetica)),Nyroca_leucostomum)),Cyriopagopus_glaucescens),Morelia_cyanogaster),(Castor_kraepelini,Fregilegus_murinus)),Gypaetus_caelebs),Kinixys_himalayensis),Streptopelia_leptochelis),(Leiopython_subcinctus,Xenophrys_himalayanus)),Osteopilus_unicolor),Apodora_scincus),Limnaeus_carnifex),Lepus_salei)),((Ciconia_barbatus,Squaterola_smaragdina),(Eudrornias_duplus,Siniperca_lavaretus))),Sceloporus_adspersus),(((((((((((Aegialifes_stimsoni,Chondropython_dentata),Pica_altaicus),Teratoscincus_fimbriatus),((((Bos_tricolor,Ptychozoon_barroni),((Corvus_azureus,Regulus_colchicus),Phylloscopus_perdix)),Larus_ovata),((((Lampropeltis_paganus,Lobipes_calvus),Phelsuma_bairdi),Panthera_giganteus),Thecla_cygnus))),Castor_hypomelus),(Alectoris_doriae,(Psalmopoeus_zagrosensis,Rhynchaspis_alpinus))),Vulpes_chinensis),Iguana_cornix),Branta_maldivarum),Tropidurus_cinereus),((((((((Burhinus_difficilis,Desnana_keyzerlingii),Chelus_epops),Petrocincla_flavirufa),Ruticilla_thibetanus),Nemachilus_shadini),Margaritifera_siebenrocki),(Chamaeleo_asperum,Sphenops_cenchria)),Middendorffinaia_meermani)),Alcedo_hilarii);
Morelia_cyanogaster Enhydra_rostratus

((((((((((((Acanthis_japonica,(Bradypterus_madagascariensis,Buthacus_troglodytes)),(((Branta_crassidens,((Furcifer_multifasciata,Uromastyx_canorus),(Margaritifera_vanellus,Vulpanser_ladogensis))),Megaloperdix_sepsoides),(Eremophila_ceterus,Hemitheconyx_stellio))),(((((((Anas_elaphus,((Chrttusia_interiorata,Squaterola_rufinus),((Cuon_leucoptera,((Eucratoscelus_bonasus,Micropalama_similis),Oligodon_zagrosensis)),Gekko_carnivorus))),Psammophis_bicinctores),Seokia_hilarii),Rhamphiophis_gebleri),Asthenodipsas_alba),Osteopilus_vulpes),Sterna_not)),Capra_lutra),((Callipogon_clericalis,((Gypaetus_dentata,Tetraogallus_aegagrus),Phrynomerus_horridum)),Natriciteres_subglobosa)),Lanius_duplus),((((Anser_edulis,(((Avicularia_caeruleus,Lyrurus_weberi),Tursiops_rubicola),Capreolus_glutinosus)),Pareas_dahurica),Calidris_altaicus),(((((Charadrius_graculus,Ethmostigmus_campestris),Sus_septentrionalis),Cygnopsis_prasina),Trapelus_aceras),(Euspiza_plumipes,Sus_vastus)))),(Boiga_dominicus,Pyxicephalus_nivalis)),(Boa_ferrumequinum,Pandinus_botnica)),Larus_lividum),Sitta_turtur),((((((Accipiter_fuellebornii,Sturnus_mitratus),Eryx_riparia),Opheodrys_borealis),(Chen_leucogaster,(Chlamydotis_teguixin,Sitta_sepsoides))),Telescopus_sibiricus),Parnassius_crassicauda),((((((((((((((Allobates_pulchripes,(Anthropoides_dubia,Branta_tarandus)),Chen_isabellina),(Branta_eremita,Uromastyx_longipes)),Kaloula_perdix),Rhynchaspis_capra),Athene_mykiss),Kassina_rupestris),Opheodrys_ampullatus),(Fulica_noctua,Paramesotriton_guttata)),Latastia_canorus),(Candoia_flava,Grus_uncia)),Cuon_cyanus),Xenopeltis_kuhli),((Ambystoma_imperator,Egretta_tataricus),Capella_baibacina)));
Hemitheconyx_stellio Opheodrys_borealis

(((((Acanthogonatus_rubicola,Nipponia_dendrophila),Porzana_lagopus),(((((Ahaetulla_intermedia,(Macrorhamphus_rudicolis,Phalaropus_not)),Carabus_salvator),((Capreolus_gobio,(Eublepharis_scrofa,Ptyodactylus_thibetanus)),Philacte_gibbosus)),Motacilla_torquata),Vulpes_celer)),(Allactaga_weliczkowskii,((Dasypeltis_zagrosensis,Sturnus_carnivorus),Monodon_japonica))),(((((((Acanthoscurria_bellii,Phalaropus_fusca),Plegadis_hyperboreus),(Damon_ruficollis,Spalax_merganser)),Phoca_medirostris),(Cynops_lepturus,Rosalia_middendorffi)),Pagophila_hispida),Thymallus_dauricus),(((((Acheron_crassidens,((Hemitheconyx_collectivus,Marmota_gregarius),Riparia_dolosus)),Scolopax_deminutus),(((((((((((Aegypius_kurilensis,Pratincola_grandis),Apalone_armeniacus),(Perdix_stylifer,Rhynchophis_paradisi)),(Dipus_galactonotus,Pusa_ferox)),Corytophanes_tatarica),(Rhombomys_albicilla,Tupinambus_totanus)),(((((((Amphiuma_caeruleus,(Corytophanes_meles,(Ethmostigmus_subruficollis,Osteopilus_subglobosa))),(Nemachilus_vermiculatus,Sceloporus_noctua)),Clemmys_atra),Citellus_flava),Glareola_chrysaetus),(((Gekko_aestivus,Hydrochelidon_picta),(Querquedula_collaris,Rhinolophus_ignicapillus)),Siniperca_madagascariensis)),Sceloporus_deminutus)),Corvus_leucopsis),Antaresia_graeca),((((((((Alectoris_rubida,Sorex_coturnix),Upupa_undulata),(((Alopex_aegagrus,(Caiman_margaritifera,Fregilegus_insignis)),Eudramias_falcipennis),Pyxicephalus_limosa)),Onychodactylus_viridescens),((Ketupa_novaeguineae,Plethodon_leucoryphus),Leuciscus_auratus)),Gyps_quadrivirgata),Eutamias_floridana),Haliaetus_odoratus)),(((((Antilope_americanus,(Buthacus_hosii,Phylloscopus_teguixin)),((Eudrornias_lesueurii,Scaphiopus_aceras),(Eumeces_xanthocheilus,Odonthurus_flavirufa))),Babycurus_mlokosiewiczi),Scolopendra_ciliatus),Castor_morinellus))),Telescopus_cygnoides),Alcedo_heudei));
Macrorhamphus_rudicolis Amphiuma_caeruleus

(Acanthoceros_aegagrus,((((((((((Aegialifes_intermedia,Alcedo_felderi),(Bradypterus_caninus,Enhydra_cristatella)),((((((Anodonta_erythronota,((((Chrysopelea_flavomaculatus,(Lamprophis_hardwickii,Pelusios_subrubrum)),(Hirundo_sirtalis,Synthliboramphus_caelebs)),Gekko_tanganicus),Scorpio_scripta)),(Cottus_walti,(Grammostola_dennysii,Saxicola_caryocatactes))),Iguana_fragrans),Oedura_hemilasius),((((Chrttusia_falcipennis,Net_fischeri),Emydura_jaculus),Ethmostigmus_regius),Phylloscopus_mugodjaricus)),Passer_riparia)),((Ctenotus_pardalis,Podoces_indicus),Thamnophis_jubata)),Sterna_rudicolis),((((((Agama_nebrius,((((((Allobates_borealis,Kaloula_completus),(Ctenosaura_vulgaris,Rissa_monilis)),Dahurinaia_tricolor),((Parabuthus_cristatus,Tadorna_molurus),Platemys_teniotis)),Chrttusia_fiber),(Margaritifera_gallicus,Megophrys_pelagicus))),(Heteroscodra_gobio,Petrocincla_fasciata)),((Alaus_Anas,Eudramias_mykiss),(Phrynosoma_dexter,Spalerosophis_torquata))),Heteroscodra_marcianus),((Buthacus_nupta,Regulus_moschiferus),Canis_brevirostris)),((((Corvus_weberi,Pusa_barroni),Zosterops_carnifex),Corytophanes_pugnax),((Eublepharis_murinus,(Net_pyromelana,((Pelusios_mystaceus,Scolopendra_altaicus),Teratolepis_graeca))),Myotis_jubata)))),Columba_manul),(((Boiga_geyri,(Phrynocephalus_kazanakowi,Tropidurus_mirabilis)),Otocoris_mlokosiewiczi),Pelodytes_kuhli)),Phalacrocorax_felderi),((Aphonopelma_acuta,(Ctenotus_marinus,Petrocincla_chuatsi)),Phylloscopus_teguixin)),((((((Aegialifes_reticulatus,Varanus_carnifex),Rhombomys_fiber),Pelusios_minor),Rhabdophis_rufus),(((Boiga_fiber,Eublepharis_prasina),Litoria_angustirostris),Ziphius_flavolineata)),((Arenaria_vermiculatus,Damon_porzana),(Citellus_calligaster,(Scincus_monoceros,Sorex_fiber)))));
Platemys_teniotis Ctenosaura_vulgaris

((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((Xenopeltis_constricticollis))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))Alopex_tridactylum))))));
Xenopeltis_constricticollis Alopex_tridactylum

((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((Xenophrys_uluguruensis)Tropidurus_ceterus)Trachemys_albopillosum)Totanus_keyzerlingii)Thecla_nigropalmatus)Testudo_adamsii)Synthliboramphus_taczanowskius)Sturnus_calamita)Strepsilas_interiorata)Siniperca_musculus)Scincus_leucophtalmos)Rhombomys_marmorata)Regulus_maculata)Python_clarus)Ptyodactylus_dauricus)Pterocles_himalayensis)Pratincola_cristata)Physignathus_cliffordii)Phrynocephalus_occitanus)Phoca_ulikovskii)Phalacrocorax_macqueni)Pelusios_not)Pelomedusa_strepera)Pelodytes_platycephala)Passer_stimsoni)Parus_insularis)Parnassius_nebrius)Pandinus_ussuriensis)Ovis_verrucosus)Otocoris_mexicanum)Otis_colubrinus)Osteopilus_mystaceus)Opheodrys_erythrogastra)Onychodactylus_kurilensis)Odobenus_unicolor)Monticola_hassanica)Minipterus_dignus)Mergus_melonotis)Meles_cocincinus)Melanocoryhpa_saiga)Macrorhamphus_fusca)Lyrurus_pyromelana)Leuciscus_gordoni)Leptopelis_crispus)Laudakia_thibetanus)Kassina_rufodorsata)Hyperoodon_celeber)Holodactylus_cygnoides)Heterodon_ruthveni)Hemiscorpius_parreyssi)Gyps_corone)Grus_bewickii)Grampus_grus)Gonyosoma_lepturus)Gallinago_albigula)Eucratoscelus_vulgaris)Eublepharis_avocetta)Ephibolus_hyemalis)Enhydris_caerulea)Enhydra_tridactylum)Emydura_haliaetus)Elseya_personata)Dyscophus_cristatellus)Dasypeltis_helena)Coenobita_classicus)Chrysopelea_capra)Chrysemys_quadriocellata)Chlamydotis_schreibersi)Chlamydotis_ferruginea)Chettussia_leucophyllata)Certhia_franckii)Camptoloma_galeatus)Camptoloma_calyptratus)Bronchocela_truncatus)Bronchocela_thibetanus)Branta_salei)Bradyporus_cyanochloris)Brachyramphus_gigas)Bombus_means)Boiga_lutris)Basiliscus_pardalis)Basiliscus_nigrolineatus)Balaena_auratus)Arctomys_piscator)Anthropoidae_bairdi)Anodonta_atrigularis)Anas_lineatus)Amphiuma_fiber)Aix_cyanogaster)Actitis_troglodytes)Actitis_taxispilota)Acipenser_japonica)Acheron_vastus)Acheron_saiga);
Arctomys_piscator Pelodytes_platycephala

(Acanthoceros_coloratovillosum,(((Acipenser_carnivorus,((Amphiuma_leucomelas,((Hottentotta_flavomaculatus,(Limnaeus_marmoratus,Remiz_duplus)),Petrocincla_sarasinorum)),((((Casarca_semipalmatus,Notophthalmus_medici),(Neophron_scincus,Pterinochilus_aureostriata)),Ursus_nigropalmatus),((Circus_riparia,(Coregonus_not,Rhinolophus_hirundo)),(Citellus_insularis,(Coturnix_armata,(Pusa_equestris,Pyrgilauda_modestus))))))),(((Castor_exanthematicus,Rhynchophis_leucomelas),(((((((Ctenosaura_pardus,Pyrgilauda_falcinellus),Tadorna_porphyrio),Prunella_lagopus),Enhydra_holbrooki),Nucifraga_indicus),Rhesus_tristis),Hyperoodon_caninus)),Xenophrys_avocetta)),Cuon_aegagrus),((((((((Almo_fiber,Casarca_deminutus),((Buteo_subcinctus,(Ctenosaura_morinellus,Porphyrio_boa)),Callipogon_mystaceus)),Morelia_perdix),Rufibrenta_cingulata),Phrynomerus_flavirufa),(((Archispirostreptus_purpurascens,Bradyporus_caerulea),Enhudra_leucoryphus),((((((((((((Asthenodipsas_arvensis,Hemitheconyx_perdix),Chlamydosaurus_gobio),Gerrhosaurus_zenobia),(Columba_oenanthe,Hirundo_verrucosus)),Zosterops_molurus),(((((Citharacanthus_gratiosa,Tamias_yeltoniensis),Sphenurus_kurilensis),Heterodon_leucomystax),Pelodytes_gratiosa),(Leiurus_stagnalis,Rangifer_carinatus))),Enhydra_communis),Perdix_plumipes),(((Candoia_lopatini,Elaphe_cristatus),Phoca_baibacina),Pterinochilus_eximia)),Erpeton_truncatus),((((Balaenoptera_tarda,Hirundo_hosii),(Boa_interiorata,(Brachypelma_personata,Neolycaena_sagrei))),(((((Circus_purpurascens,Cuon_deremensis),Totanus_kuhli),Lobipes_sibirica),(Leiopython_bimaculata,Sorex_atthis)),((Ingerophrynus_notaeus,Limosa_garmani),(Mylopharyngodon_shadini,Pterinochilus_japonensis)))),(Lamprophis_celer,Lystrophis_dentatus))),((Chelus_Jankowskii,Limosa_cavimanus),Saiga_lasiopterus)))),Hysterocrates_chrysargos),Pareas_pulchra));
Phrynomerus_flavirufa Acipenser_carnivorus

(((Actitis_carbonaria,Coregonus_ladogensis),Salvelinus_ovata),((((((((((((((Aegialifes_salei,(Ciconia_cinclus,Tropidurus_multifasciata)),Allactaga_leucocephala),Coenobita_compactus),(Charadrius_viridescens,Sericinus_Bernicla)),Athene_erythrogastra),((((((Aix_multituberculatus,((Chrysopelea_turneri,Elaphe_modestus),Ethmostigmus_fluviatilis)),Osteopilus_adspersus),(Ketupa_dives,Tupinambus_leucoryphus)),Boa_sinensis),Dendrelaphis_trianguligerus),(Phylloscopus_medirostris,Tringa_Jankowskii))),Regulus_sauritus),Lanius_laevis),Desnana_amboinensis),Hottentotta_mykiss),(Eulabeia_maritimus,Paradoxornis_pyromelana)),Querquedula_cinaedus),(Crocodylus_parahybana,(((Equus_virgo,Falcipennis_sp),(Limnodromus_sepsoides,Nyroca_vipio)),Pagophila_aestivus))),(((Anthropoidae_classicus,(Arenaria_cranwelli,(Bufo_tuberculosus,Epipedobates_pygmaeus))),Ctenosaura_buccata),(((Balaena_emarginatus,Chlidonias_vitulina),Gonyosoma_weberi),Psammophis_montela))),(((((Ahaetulla_albertisii,(Ambystoma_albertisii,(((((((((Anodonta_pulchripes,Lamprophis_stejnegeri),Boiga_onocrotalus),Salmo_barroni),(((((Anolis_corsac,(Ceratophrys_punctatus,Podoces_gigas)),Nucifraga_flava),Tadorna_stejnegeri),(Antaresia_geyri,(Athene_sanguinolentus,(Enhydris_teguixin,Ruticilla_adspersus)))),Lyrurus_collaris)),(Bombyx_albigula,((Bubulcus_ornata,Circaetus_gallinago),(Cuculus_ameiva,Dendrelaphis_lepturus)))),Phelsuma_apus),Haliaetus_maihensis),(Eubalaena_boa,Saxicola_quadriocellata)),(Anser_eremita,(Corallus_taeniura,(Phyllopneuste_sarasinorum,Plegadis_auratus)))))),(Dyscophus_xanthocheilus,Odobenus_gallinago)),((((Aix_zonata,((Diomedea_hendersoni,Sitta_uncia),((Megaloperdix_cyanus,Porzana_maihensis),Moschus_eulophotes))),Alaus_smaragdina),Apodora_teguixin),(Ceratophrys_ibis,(Mesoplodon_plathyrhychos,Osmoderma_hyemalis)))),Clemmys_macrops),Aquila_obsoleta));
Ceratophrys_ibis Bufo_tuberculosus

(,,,,,,Trionyx_filipjevi,,,,,,,,,,,,,,,,,,,,,,,,,,,,Lutra_minutus,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,);
Trionyx_filipjevi Lutra_minutus

((((((((Abantias_punctatus,Cuculus_stellio),(Budytes_bimaculata,Uromastyx_alterna)),Pituophis_canagica),((((((((((((Actitis_imperator,Coenobita_versicolor),(((((Burhinus_leucotus,(Certhia_intermedia,(Coleonyx_hemionus,Cygnus_cinereus))),Underwoodisaurus_sibiricus),Latastia_viscivorus),((Oenanthe_cherrug,Ptychozoon_alpestris),Rhodostethia_helena)),Hemiscorpius_torquata)),(Sitta_atriceps,Sterna_alpina)),(Circaetus_arizonensis,(Mogera_citrsola,Zosterops_ferrumequinum))),(((Bradypodion_fulva,Tetrao_weliczkowskii),Furcifer_collybitus),Phelsuma_rufus)),Mylopharyngodon_peregusna),Cyriopagopus_licin),((Bombus_lepturus,(Gecarcinus_pallasii,(Paradoxornis_cristatus,Pareas_collybitus))),Chlamydotis_ornata)),((Hydrosaurus_leucoryphus,Zosterops_caudatus),(Meles_vastus,Panthera_giganteus))),(Colaeus_insignis,Porzana_eximia)),Uromastyx_pallasii),Pachytriton_physalus)),Bradypodion_apollo),Myotis_perdix),Ingerophrynus_teguixin),((((((((Acanthosaura_cavirostris,Callipogon_medirostris),Gallinago_lividum),((((Anas_torquatus,(((Bombus_maurus,Bradyporus_fulvus),(Nemorhaedus_vanellus,Pyxicephalus_erythronotus)),Cardiocranius_cachinans)),(Bos_pelagicus,Monodon_weliczkowskii)),(Nucifraga_boyciana,(((Pelusios_major,Spalax_marinus),Xenopeltis_linaria),Rhabdophis_enydris))),Canis_regius)),Hydrochelidon_hipposideros),Alpes_eremita),((Agama_melanoleucus,Boiga_mexicana),Phrynocephalus_garulla)),Saga_nippon),Phrynosoma_cepediana),(((((Acanthoscurria_weberi,(((Atrophaneura_bellii,Cyriopagopus_avocetta),(((Aythia_ceterus,Rosalia_pallasii),Selenocosmia_macrops),((Circaetus_krueperi,(Coregonus_leucomelas,(((Cynops_fulvus,Cypselus_mystacinus),Upupa_lividum),(((Eunectes_himalayensis,(Petrocincla_collybitus,Sternotherus_milii)),Lepus_clinatus),(Pachydactylus_eremita,Pterocles_tuberculosus))))),Salvelinus_ameiva))),Emberiza_pictus)),Synthliboramphus_crispus),(Ambystoma_mugodjaricus,Chrysopelea_exanthematicus)),Certhia_keyzerlingii),Brachypelma_femoralis));
Alpes_eremita Monodon_weliczkowskii

(Abantias_arcticus,((((((Abantias_tigrinus,(Pachytriton_stejnegeri,Pagophila_hemionus)),Canis_baibacina),(Chrttusia_sphenocercus,Hydrosaurus_karelini)),(((Bufo_floridana,Pandinus_pusilla),Philacte_galericulata),Opheodrys_tarda)),Phyllopneuste_aleutica),(((((((Alloporus_rusticolus,Ptychozoon_atra),Camptoloma_sebae),Net_scutulata),Chrysemys_schneideri),Madagascarophis_yeltoniensis),Leptopelis_davidiana),(Ameiva_melanoleucus,Otis_troglodytes))),(((((((((((Actitis_temminskii,(Philacte_cyanea,Teratolepis_corticale)),Xenochrophis_albigula),Emydura_sauritus),Euspiza_saiga),((((Apus_nigropalmatus,Aquila_parahybana),Tamias_septentrionalis),(Cuora_platyrhinos,Pagophila_manul)),Middendorffinaia_physalus)),Ophisops_nigriceps),Riparia_mackloti),Pelusios_scutulata),Geochelone_enydris),(Amphiuma_deminutus,Tamias_hongkongensis)),((((((((((((((((((((((((((Aegialites_horridum,((((Apodora_hemionus,(Bombus_heliaca,Phyllopneuste_pelagicus)),Ortigometra_oedicnemus),Platalea_adspersus),Sphenops_Jankowskii)),(Emydura_clericalis,Teratoscincus_perdix)),Pusa_vittatus),Athene_musculus),(Gonyosoma_fuscatus,Lystrophis_reinwardti)),Pogona_argali),((((Circus_naumanni,Corallus_truncatus),Ptyodactylus_ion),((Citellus_battersbyi,Lanius_gemmicincta),(Natriciteres_buccata,Terpsihone_labiatus))),(Epipedobates_aegagrus,Tylototriton_sepsoides))),(Latastia_borealis,Sericinus_naumanni)),(Damon_carbonaria,Lasiodora_collybitus)),Tropidurus_ladogensis),(Phrynocephalus_ameiva,Saga_brevirostris)),Chondropython_fernandi),Leuciscus_fuscus),Apodora_docilis),Squaterola_linaria),Pica_calidris),Eschrichtius_blakistoni),((((Aplopeltura_cyanogaster,Dafila_ruthveni),Sternotherus_sarasinorum),Pandion_nigra),Nipponia_atrigularis)),Mochlus_notaeus),Madagascarophis_avinivi),(Arenaria_obsoleta,Coregonus_maurus)),(Capra_brandtii,(Rhynchophis_dives,Theloderma_sinensis))),Lutra_pardalis),Homalopsis_constricticollis),((Alloporus_galeatus,Cyclemys_guangxiensis),Sitta_pardalis)),(Buthus_pygargus,Perdix_brachydactyla))));
Rhynchophis_dives Nipponia_atrigularis

((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((Xenophrys_leucostomum)Vulpanser_nippon)Vormela_bengalensis)Uroplatus_taeniura)Uromastyx_dendrophila)Tylototriton_onocrotalus)Turdus_hypoleucus)Thecla_undulata)Thecla_meles)Teratolepis_canorus)Tamias_caryocatactes)Sturnus_strepera)Sphenurus_enhydris)Spalerosophis_sphenocercus)Scaphiophryne_variabilis)Salvelinus_lobatus)Salvelinus_chinensis)Recurvirostra_helena)Recurvirostra_caudicinctus)Pseudemys_leucomelas)Pratincola_mycterizans)Porzana_yeltoniensis)Porphyrio_borealis)Pogona_compactus)Plegadis_thibetanus)Phyllopneuste_deminutus)Phelsuma_stylifer)Paramesotriton_bicinctores)Pachytriton_temminckii)Osteopilus_armeniacus)Oedura_acutus)Odobenus_gemmicincta)Numenius_minutus)Nemorhaedus_himalayanus)Monodon_leucomelas)Mesoplodon_graculus)Megaptera_barbatus)Megaloperdix_melanuroides)Lycodon_lopatini)Leuciscus_krueperi)Lepidobatrachus_getula)Leiocephalus_adspersus)Latastia_nupta)Latastia_horridum)Latastia_getula)Latastia_adspersus)Lamprolepis_melanoleucus)Kinosternon_griseus)Iomachus_hongkongensis)Hydrosaurus_filipjevi)Heteroscodra_bifasciatus)Hemitheconyx_caerulea)Grus_bimaculata)Gonyosoma_gregaria)Gongylophis_himantopus)Eublepharis_acanthinura)Eryx_hypoleucus)Epicrates_cyanus)Emberiza_pallasii)Cyclagras_flavigularis)Cuculus_hirundo)Crocodylus_crispus)Corallus_atrigularis)Chrttusia_nippon)Chlamydotis_nigra)Carabus_tataricus)Buteo_valliceps)Burhinus_Bernicla)Branta_siebenrocki)Branta_seemani)Bradyporus_exanthematicus)Brachyramphus_livia)Brachypelma_mugodjaricus)Balaenoptera_exquisita)Aythya_arizonensis)Apodora_himalayensis)Apodora_cyanea)Aphonopelma_tinnunculus)Aphonopelma_completus)Almo_mexicana)Allobates_trianguligerus)Ahaetulla_flavigularis)Aegialites_sinensis)Accipiter_sauromates)Acanthoscurria_margaritifera)Acanthoscurria_aspera);
Scaphiophryne_variabilis Aphonopelma_tinnunculus

(,(((((((,),),),),((((((((,),),),),(,)),),),)),),((((,),((,),)),),)),(((((((((((((((((,((((,),),),)),((,),)),((((((((((((((,),(,)),),((((,(((,),),)),),),)),),),(,)),),),),),),),(((((,),),),),))),(((,(,)),(,)),((,),(,)))),),),),),),),),Amphiuma_kuhli),),),(Alectoris_helena,((,),))),((,(,)),)),(((,),),)));
Amphiuma_kuhli Alectoris_helena

(((((Acanthoceros_boyciana,((Balaenoptera_caudolineatus,Butastur_maculata),Leiocephalus_salei)),Rhombomys_cygnoides),Bradypodion_rostratus),(Bombyx_viridescens,((Dasypeltis_tristis,(Hottentotta_subrufa,sibiricus_sp)),Enhudra_rubida))),(((((((((((((Agama_sauritus,Calidris_maritimus),(((((((Chelydra_baibacina,Coturnix_atthis),Pelecanus_kopsteini),(((Fuligula_rufodorsata,Saiga_apollo),(Lyrurus_aegagrus,Perdix_tigris)),(Pica_blythi,Rhynchophis_melanostictus))),Testudo_coelestis),Phyllopneuste_murinus),Onychodactylus_wumuzusume),(Egretta_macrops,Limosa_fischeri))),((Eremophila_shadini,Passer_proteus),Nerodia_zagrosensis)),Branta_leucocephala),(((((((((((((((((Aphonopelma_melanostictus,Saxicola_emarginatus),(Athene_exanthematicus,Bombus_scutulata)),Limnaeus_aristotelis),Otis_fusca),Eublepharis_taczanowskius),Dipsosaurus_caudata),Salmo_labiatus),((Bradypodion_fiber,Oenanthe_chrysaetos),Cuora_noctua)),Monodon_auriculatus),Python_gallinago),Arctomys_taxispilota),((((Certhia_flavescens,Tringa_Bernicla),Iomachus_rusticolus),Phyllopneuste_scalaris),Latastia_smithii)),(((Charadrius_geyri,(Gekko_gemmicincta,Parus_caesius)),Notophthalmus_nelsonii),Phasianus_scutulata)),Phrynosoma_glutinosus),((Camptoloma_albertisii,(Prunella_galeatus,(Tadarida_rubicola,Thecla_moschiferus))),Paradoxornis_circia)),(Dyscophus_clarus,Nemachilus_falcinellus)),Sus_flavescens)),((((Burhinus_porphyrio,Laudakia_collectivus),Hemitheconyx_cliffordii),Pelecanus_truncatus),(((Hadrurus_azureus,Leptopelis_schrencki),Madagascarophis_arcticus),Pachytriton_gibbosus))),(((((Boiga_tetrix,(Pituophis_elegans,Trachemys_dendrophila)),(Mareca_orientalis,Phalaropus_korschun)),Pogona_pygargus),Gonocephalus_cristatellus),((Gonyosoma_tarda,(Laudakia_gordoni,Poephagus_australis)),Nipponia_maldivarum))),Pterocles_miliaris),(Chlidonias_verrucosus,Pterinochilus_torquatus)),Netta_medirostris),Margaritifera_grandis),((Bombina_canorus,(sibiricus_completus,sibiricus_nigriceps)),(Ephibolus_pardalis,Procellaria_erythrogastra))),Oedura_rufus),Antilope_leiosoma);
Hadrurus_azureus Notophthalmus_nelsonii

((((Acanthogonatus_pygmeus,Margaritifera_fuellebornii),Scorpio_teguixin),Gazella_gigas),(((((((Acanthoscurria_sieboldii,Plethodon_unicolor),Holaspis_pictus),Xenochrophis_emilia),((Anas_avinivi,Ctenosaura_salei),(((Buthacus_cancerides,((Dasypeltis_dominus,(Dryobates_galeatus,Osteopilus_borealis)),Falco_caudata)),(Egretta_regius,Philomachus_salei)),Rhodostethia_means))),Dyscophus_monedula),Lasiodora_mehelyi),(((((Aix_vitulina,Margaritifera_perdix),((((Alaus_leucophyllata,((((((((((((((((Balaena_docilis,((((Callipogon_indicus,Mogera_cavimanus),Tetraogallus_alba),Iomachus_squamatus),Dendrobates_caesius)),((Lobipes_equestris,Psammophis_cornix),Osmoderma_pallasii)),(((Cyclemys_dorsalis,Vipera_valliceps),Myotis_minor),(Heteroscodra_barroni,Tylototriton_hongkongensis))),Certhia_leptochelis),(Hottentotta_nivalis,Polypedates_calligaster)),(Cottus_drapiezii,(Kinosternon_holbrooki,Phrynops_decorus))),Columba_tenuirostris),Capeila_personata),(Eudrornias_lagopus,Limnodromus_parahybana)),Rhynchophis_exquisita),(Chlidonias_nivalis,Corvus_conicus)),(((Diomedea_middendorffi,Tetrao_cinaedus),Glareola_rhymnus),Megaloperdix_caudolineatus)),((((((Chelydra_baeri,Kaloula_monorhis),Chelydra_nupta),Tadorna_ladogensis),((Gyps_dennysii,Haliaetus_interpres),Sericinus_fluviatilis)),(Mesoplodon_novaeguineae,Podoces_wogura)),((Lamprolepis_constrictor,Larus_uncia),Scincus_longipes))),Recurvirostra_fuscus),Corvus_avinivi),(Pelodiscus_zagrosensis,Querquedula_bedriagai))),(Branta_mutabilis,Gekko_amboinensis)),(((Chlamydotis_physalus,Dahurinaia_calidris),(Oligodon_mystacinus,Underwoodisaurus_emilia)),(Cuora_corone,Salvelinus_wogura))),(((Capreolus_falcinellus,Philothamnus_carnivorus),Colaeus_celeber),Milvus_albirostris))),Riparia_percnopterus),((Antilope_tigrinus,(((((((Bufo_resinifictrix,Oceanodroma_brevirostris),Iomachus_leiosoma),Iguana_caudatus),Hyla_canus),Podoces_calligaster),Cypselus_helvetica),Pyxicephalus_equestris)),Eremophila_naumanni)),Eryx_major)),Acheron_mongolica);
Dahurinaia_calidris Scincus_longipes

((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((()))))))))))))))))))))))))))))))))))))))))))))))))Limosa_hassanica)))))))))))))))))))))))))))Chlamydosaurus_alterna)))))))))))))))))));
Limosa_hassanica Chlamydosaurus_alterna

(((Abantias_atra,(((((((((((((((((((((Anas_bimaculata,Pica_leucotus),(Ephibolus_chrysaetus,Eschrichtius_torquata)),((Burhinus_gallinago,Vulpes_cyanogaster),((((((Gecarcinus_melleri,(Homopholis_vastus,Rhinolophus_sibirica)),Meles_lepturus),Poephagus_brandtii),Lasiodora_septentrionalis),Rhacophorus_duplex),Myotis_leucocephala))),(Basiliscus_hongkongensis,Rufibrenta_anachoreta)),((Cyclemys_shadini,((Haliaeetus_prasina,Rhodostethia_radiata),(Phrynohyas_pardus,Thymallus_tanganicus))),(Holaspis_gallinago,Pareas_trianguligerus))),Avicularia_guttifer),Morelia_shadini),((Chlamydosaurus_jaculus,Pareas_rutilans),((Cottus_cioides,Dasypeltis_isabellina),Kaloula_parreyssi))),Zosterops_chinensis),Motacilla_porphyrio),Rhacophorus_scrofa),Siniperca_smithi),(Aplopeltura_torquata,Parnassius_bifasciatus)),Damon_scrofa),Pelomedusa_dentatus),Saxicola_collybitus),(Melanocoryhpa_eximia,Parabuthus_albopillosum)),Geochelone_rutilans),Gonocephalus_bewickii),Eucratoscelus_coelestis),(Citharacanthus_hassanica,Poephagus_decorus))),Balaenoptera_dennysii),(((((((((((Alcedo_duplex,Hottentotta_blakistoni),((Chelodina_nigropalmatus,Selenocosmia_duplus),(((Chrttusia_celeber,Parnassius_pulchra),Pusa_hypoleucos),Hyperoodon_grus))),((Amphiuma_meles,(((Anolis_hasselquistii,Bradypodion_bewickii),Pusa_politus),((Archispirostreptus_paradisi,Pelodytes_sarasinorum),Scolopax_martensi))),Sterna_multituberculatus)),(((Eremophila_peregrinus,Recurvirostra_mykiss),Philacte_tentaculatum),Phylloscopus_ichthyaetus)),(Dasypeltis_perrotetii,Ovis_cinaedus)),(Philomachus_lasiopterus,Pseudorca_melleri)),Nipponia_striatus),Aphonopelma_emilia),Pandion_subniger),Charadrius_guttata),((Ambystoma_celer,(Bombyx_zagrosensis,((Chettussia_cyanochloris,Leiurus_grunniens),Machetes_subminiatus))),((((Aythya_calvus,Eudrornias_alpinus),(Boa_fuscatus,Phrynocephalus_edulis)),Gyps_pictus),Bos_porphyrio))),Allactaga_ferrumequinum);
Pseudorca_melleri Hyperoodon_grus

(Acanthoceros_melonotis,Accipiter_turtor,Acipenser_holbrooki,Actitis_modestus,Aegialifes_coelestis,Agama_cambridgei,Antilope_papuana,Argynnis_dexter,Basiliscus_avosetta,Boa_flavescens,Bradyporus_caudicinctus,Budytes_colombianus,Buteo_onocrotalus,Buthacus_aestivus,Callipogon_ichthyaetus,Candoia_leucostomum,Cardiocranius_trigonopodus,Certhia_hypoleucus,Charadrius_collectivus,Chelodina_alterna,Cinclus_avocetta,Coleonyx_schokari,Coturnix_dulkeitiana,Cuon_albicilla,Cyclagras_azureus,Cygnus_sinensis,Dasypeltis_sebae,Dipsosaurus_fallax,Egretta_crassidens,Enhydra_physalus,Epicrates_nippon,Epipedobates_tanganicus,Ethmostigmus_pugatshuki,Eubalaena_crucigera,Eudrornias_pholeter,Gongylophis_canus,Gongylophis_glottis,Gonyosoma_medici,Hadogenes_hodgsoni,Haliaeetus_murinus,Haplopelma_leucorodia,Hemiscorpius_aleutica,Heteroscodra_fluviatilis,Homopholis_bedriagai,Hyperoodon_bifasciatus,Kaloula_chrysaetus,Kassina_ammon,Kassina_reticulatus,Kinosternon_plathyrhychos,Leiocephalus_gratiosa,Lobipes_pachypus,Lycaenopsis_stagnalis,Machetes_reticulatus,Meles_castus,Meles_chrysaetus,Nemachilus_truncatus,Notophthalmus_pyromelana,Nyctixalus_mystacinus,Opheodrys_latiscutatus,Opheodrys_subglobosa,Oxyura_edulis,Paradoxornis_iankowskii,Pelecanus_leucogaster,Pelodytes_tristis,Perdix_paradisi,Phalacrocorax_erythrogastra,Phelsuma_vereda,Philacte_sauritus,Phrynohyas_filipjevi,Phrynops_bimaculata,Phrynops_capra,Phrynosoma_erythronota,Porzana_cristatellus,Pterinochilus_scalaris,Rhynchophis_lutra,Saga_scrofa,Salamandra_sp,Salvelinus_quinquestriatus,Sceloporus_griseus,Sitta_cygnus,Sphenops_pulchra,Sus_oxycephalum,Tadarida_dentatus,Testudo_scabra,Tetrao_molurus,Tetrao_platyrhinos,Tiliqua_leucogaster,Tryngites_sujfunensis)Abantias_proteus;
Tetrao_platyrhinos Buthacus_aestivus

(,,,,,,,,,,,,,,,,,,,,,,,,,,,,Egretta_colombianus,,,,,,,,,,,,,,,,,,,,,,Leiurus_schneideri,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,);
Egretta_colombianus Leiurus_schneideri

((((((Accipiter_aegagrus,Bombus_lineatus),(Fuligula_flava,Rhynchophis_plathyrhychos)),(Alpes_euptilura,((Anas_bifasciatus,Bronchocela_cygnus),(Cottus_interpres,Lamprophis_vastus)))),((((((((((((Allobates_sanguinolentus,Bos_interiorata),Carabus_limosa),Natriciteres_situla),((Basiliscus_dignus,Caiman_sibirica),Canis_ladogensis)),(Enhydris_teniotis,Lanius_paradoxus)),(Capella_maritimus,Oxyura_turtur)),Myotis_solitaria),(Leiocephalus_crassicauda,Nemorhaedus_vittatus)),Megophrys_ridibundus),(((Bombyx_ovata,(Charadrius_jaspidea,Enhudra_tinctorius)),Chlamydosaurus_lopatini),Brachypelma_gibbosus)),Phylloscopus_bicinctores),Oligodon_vermiculatus)),(Chondropython_fimbriatus,Rhacophorus_corticale)),(((((((Acheron_noctua,Chlamydosaurus_dauricus),((Camptoloma_tuberculosus,(((Corytophanes_guttata,Mergus_savignii),Scaphiopus_sibilans),Gavia_garulla)),(Rhacophorus_cavirostris,Strepsilas_proteus))),Cardiocranius_nasicus),Phalaropus_rufina),Parnassius_stellio),(((Homopholis_hyperboreus,Sphenurus_vastus),(((Kassina_parvus,Philothamnus_rapax),(Numenius_caudolineatus,(Panthera_arcticus,Sus_eulophotes))),Squaterola_paganus)),(Oligodon_crispus,(Oligodon_sibilans,Plethodon_oedicnemus)))),((((((((Anas_pallasii,(Hadogenes_carinatus,Rhesus_cepediana)),Kassina_cristatus),Recurvirostra_prasina),(((((((Chelodina_decorus,(Philothamnus_arvensis,(Phoca_barbata,Platalea_niloticus))),(Pelusios_zagrosensis,Polypedates_vitulina)),Grampus_albopillosum),Neolycaena_dispar),(Pleurodeles_multituberculatus,Triturus_ion)),Cuora_canus),Ovis_emarginatus)),(((Aythia_alcinous,Geochelone_manul),Pituophis_longipes),Crotaphytus_perrotetii)),((((Leiolepis_caniceps,(Pachydactylus_tristis,Pyxicephalus_cachinans)),Uromastyx_crispus),(Python_mandarina,Sorex_physalus)),Milvus_viscivorus)),((Capreolus_anatina,Coregonus_tuberculosus),Osteopilus_flava)),Pyrgilauda_albertisii)),Aegialifes_erythropus);
Pachydactylus_tristis Neolycaena_dispar

(,,,,,Antaresia_insignis,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Totanus_calligaster,,,,,,,);
Totanus_calligaster Antaresia_insignis

(Zosterops_oedicnemus,Ursus_breitensteini,Upupa_monacha,Uncia_ferrumequinum,Tiliqua_aegyptia,Scaphiophryne_naumanni,Saxicola_tataricus,Salmo_sirtalis,Rufibrenta_vegans,Rhacophorus_deremensis,Procellaria_avicularia,Poephagus_pygmaeus,Plegadis_felderi,Platemys_celeber,Phylloscopus_ammon,Phrynops_prasina,Phrynops_major,Phrynocephalus_battersbyi,Phasianus_trigonopodus,Parus_aspera,Panthera_pallasii,Ovis_glottis,Opheodrys_schneideri,Oligodon_iguana,Nyctixalus_cavimanus,Nipponia_getula,Motacilla_musculus,Monodon_apus,Monachus_plumifrons,Minipterus_vitticeps,Mareca_caerulea,Madagascarophis_obsoleta,Mabuya_metallica,Lycaenopsis_clypeatus,Lobipes_merganser,Leptopelis_femoralis,Leiurus_constrictor,Lampropeltis_guangxiensis,Ketupa_leschenaultii,Hysterocrates_eximia,Heteroscodra_fusca,Heteroscodra_bewickii,Grus_capreolus,Grammostola_mystaceus,Gazella_subglobosa,Gavia_sp,Fregilegus_hendersoni,Falco_armeniacus,Eremophila_niloticus,Equus_martensi,Ephibolus_indicus,Cypselus_gibbosus,Cynops_dives,Cynops_compactus,Cynops_clypeatus,Cygnopsis_enydris,Cyclagras_nigrolineatus,Cuora_albopillosum,Crocodylus_leptochelis,Chrysemys_coelestis,Chelodina_adamsii,Chamaeleo_caeruleus,Casarca_citreola,Camptoloma_godlewskii,Calotes_vulgaris,Calotes_tristis,Burhinus_corone,Brachyramphus_nebrius,Bos_cristatellus,Bombycilla_medici,Bombus_borealis,Apodora_corticale,Anser_amboinensis,Amphiuma_pardus,Amphiuma_meles,Alopex_edulis,Alloporus_lehmanni,Allactaga_caucasicus,Ahaetulla_krueperi,Agama_pulchripes,Actitis_grus,Acipenser_variegatus)sibiricus_rostratus;
Lycaenopsis_clypeatus Ahaetulla_krueperi

(((((((((((((((((((((((,(((((((((((,),),),(((((,),),),(,)),)),(Bubulcus_enhydris,(,))),(,)),(,)),),((,),)),(,)),)),),(((,),),)),(,)),(,(,))),),),),((((,(((((,((,),)),),),),)),(((,),),(,))),),)),Rhynchophis_arcticus),),),(,(,))),),),(,)),(,)),),((((,(,)),),),)),),),),(((((((,),(,)),),),),),),(,));
Rhynchophis_arcticus Bubulcus_enhydris

(((((Acipenser_avinivi,Siniperca_krueperi),Boa_godlewskii),Tiliqua_quadriocellata),(((Anolis_flavirufa,(Chlidonias_cocincinus,Vipera_mongolica)),Heteroscodra_viridis),(((Chrysemys_strepera,Hadogenes_licin),((Otis_smithi,Salmo_czerskii),Salamandra_ibis)),(Epicrates_franckii,Mylopharyngodon_pardus)))),((((((((((((Actitis_dubia,Eudramias_nasuta),Pratincola_capreolus),Eubalaena_comicus),(Athene_barroni,Hysterocrates_reticulatus)),(((((Casarca_flava,Pachytriton_taezanowskyi),Leptopelis_schneideri),Podoces_plumipes),Vipera_regius),Machetes_medirostris)),Teratolepis_piceus),Enhydra_guttifer),Cervus_asperum),(((((((((((Allactaga_pardalis,(Regulus_dentata,sibiricus_asperum)),Citharacanthus_parreyssi),((((Aplopeltura_miliaris,(Citharacanthus_hongkongensis,Fulica_diffidens)),Epipedobates_colchicus),Parnassius_purpurascens),((((((((((((((Asthenodipsas_seemani,Gonocephalus_sibilans),Xenopeltis_ibis),((((Bombina_aleutica,((Parabuthus_battersbyi,Phelsuma_exanthematicus),Strepsilas_hipposideros)),Ciconia_placidus),Clemmys_cyanus),sibiricus_yeltoniensis)),Bradypodion_carolinensis),Myotis_torquatus),(Eurynorhynchus_hendricksoni,Rissa_cristatella)),Brachypelma_emilia),(Bufo_garullus,Phelsuma_caesius)),Gonocephalus_yeltoniensis),(Enhydris_cristata,Rhacodactylus_similis)),Sterna_caryocatactes),Aythya_vulpes),(((Emberiza_sebae,Numenius_sibilans),(Nerodia_kraepelini,Scaphiophryne_sudanensis)),Limnodromus_ferina)),Tetrao_infrafrenata))),((Calidris_javanica,Eschrichtius_saxatilis),Chondropython_clericalis)),(Pseudemys_doctus,Vulpanser_epops)),Cardiocranius_haliaetus),Lycaenopsis_colombianus),(Arctomys_tigris,Pandion_longicollis)),Ephibolus_sujfunensis),(Chlidonias_tinctorius,Python_tetrix)),(((Capella_turtur,Eulabeia_adspersus),Ptyodactylus_diffidens),Dendrobates_fragrans))),(Ctenotus_flavolineata,Pedostibes_cyanea)),(((Crocodylus_occitanus,Emydura_guangxiensis),Xenopeltis_holbrooki),Pachytriton_armata)),Caiman_barbata),(Ahaetulla_krueperi,Nhandu_guttata));
Acipenser_avinivi Salamandra_ibis

(,,,,Trapelus_caelebs,,,Testudo_flava,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,);
Testudo_flava Trapelus_caelebs

(Actitis_helena,Alauda_tinctorius,Alaus_euptilura,Ameiva_situla,Ameiva_subniger,Anas_brandtii,Aplopeltura_undulata,Apus_glaucescens,Aquila_gregaria,Atrophaneura_pica,Babycurus_hemionus,Babycurus_major,Boiga_jaculus,Branta_caudicinctus,Bubulcus_geyri,Bubulcus_jaspidea,Carabus_leucotus,Chamaeleo_collaris,Chondropython_subrubrum,Corallus_uluguruensis,Corytophanes_rubicola,Dyscophus_ferox,Egretta_azureus,Eirenis_albatrus,Enhydris_parvus,Eubalaena_himantopus,Eudramias_mycterizans,Euspiza_chrysaetos,Felis_alcinous,Furcifer_duplus,Gecarcinus_holbrooki,Geochelone_coturnix,Gonocephalus_tarandus,Grus_argali,Grus_dorsalis,Hadrurus_armata,Haliaeetus_godlewskii,Haliaeetus_sujfunensis,Halichoerus_leucogaster,Hemiscorpius_subglobosa,Heterodon_glaucescens,Homopholis_longipes,Hottentotta_karelini,Hysterocrates_buccata,Iguana_fuscus,Lagenorhynchus_subruficollis,Lamprophis_temminckii,Lanius_orientalis,Larus_acuta,Liasis_auratus,Limosa_clypeatus,Melanocoryhpa_ferina,Mogera_murinus,Nemachilus_grupus,Oceanodroma_gallicus,Oceanodroma_vegans,Oxyura_glaucescens,Pareas_septentrionalis,Pelodiscus_cocincinus,Pelodiscus_reticulatus,Phasianus_baibacina,Phormictopus_battersbyi,Phrynocephalus_acutus,Physignathus_querquedula,Plegadis_caucasicus,Podoces_rhymnus,Pratincola_salvator,Pusa_crucigera,Querquedula_subrufa,Rangifer_mnemosyne,Rangifer_smithii,Rhacophorus_avicularia,Rhynchophis_aureola,Saga_leucotus,Saiga_sieboldii,Selenocosmia_doctus,Seokia_ibera,Sericinus_crassicauda,Sericinus_stejnegeri,Sorex_carolinensis,Spalax_aeruginosus,Squaterola_mackloti,Synthliboramphus_carbo,Synthliboramphus_variabilis,Telescopus_apollo,Teratoscincus_boyciana,Terpsihone_godlewskii,Thymallus_cristatellus,Tupinambus_sibilans,Upupa_lehmanni,Uromastyx_tinctorius,Uroplatus_vastus,Vanellus_vulgaris,Vormela_franckii,Vormela_naumanni,Vormela_strepera,Zosterops_keyzerlingii)Acanthogonatus_rubicola;
Oxyura_glaucescens Bubulcus_geyri

((((((((Allactaga_zenobia,((Chalcides_lineatus,Opheodrys_crassidens),Oceanodroma_ferina)),Tadorna_flavolineata),Spermophilus_ornata),(((((Androctonus_arseniavi,((Buthacus_pulcher,((Iomachus_elaphus,Trionyx_carbo),Vulpes_bifasciatus)),Parabuthus_scripta)),Platalea_colchicus),(Remiz_nivalis,Salmo_murinus)),((((((Bombina_rostratus,Dasypeltis_geniculata),(Margaritifera_hispida,Neolycaena_krueperi)),Micropalama_vertebralis),Ruticilla_minutus),(Leuciscus_nelsonii,Phoca_caesius)),Certhia_campestris)),Milvus_lagopus)),((((((((((((((Ameiva_reticulatus,Capeila_personata),((((((Amphiuma_apollo,Ruticilla_erythrogastra),Rissa_bairdii),((Canis_stellio,Melanocorypha_fuliginosus),Trachemys_sp)),Sorex_kopsteini),Porzana_clarus),(((Bombina_anser,Chlamydotis_flavigularis),Gonyosoma_cherrug),Philacte_subruficollis))),Boa_amboinensis),((Bombus_nebularia,((((Cyclagras_cyanea,Pyxicephalus_wumuzusume),Iomachus_fasciolata),((Pelodytes_weberi,Tamias_ferruginea),Rhynchophis_limosa)),Telescopus_obsoleta)),Pachytriton_atra)),Chelodina_rusticolus),(Calidris_crassicauda,((Eurynorhynchus_striatus,Megaptera_cyanea),(Meles_thibetanus,Spermophilus_carbonaria)))),(Androctonus_aestivus,((Coenobita_sibilans,Laudakia_communis),((Gonyosoma_castaneus,Parnassius_lopatini),((Opheodrys_leucotus,Teratolepis_buccata),Phrynosoma_oedicnemus))))),Natriciteres_brevirostris),((((Archispirostreptus_clericalis,Nemorhaedus_nebrius),Circus_licin),(Dendrobates_carinatus,Rhesus_eximia)),(Citellus_monilis,(Limnodromus_albertisii,Spizaetus_tinnunculus)))),(Chondropython_schokari,(((Clemmys_anser,Gecarcinus_armeniacus),Meles_hyemalis),(Coleonyx_garullus,Pituophis_monedula)))),Neophron_grus),(((Anolis_jubata,Osteopilus_proteus),Testudo_cristatella),Milvus_zenobia)),Passer_deminutus),Numenius_infrafrenata)),Dasypeltis_amboinensis),(Bombina_deminutus,Megaloperdix_regius)),Alopex_agama,((Ambystoma_tetrix,((Corallus_trigonopodus,Homalopsis_nippon),Vipera_colubrinus)),(((Bombyx_mystacinus,Rosalia_aureostriata),(Homopholis_hemilasius,(Marmota_rutila,Porphyrio_scripta))),Pagophila_hemilasius)));
Archispirostreptus_clericalis Margaritifera_hispida

(((((Acanthosaura_fragrans,Corytophanes_pulchripes),(Babycurus_nigra,(Eumeces_temminckii,Pratincola_fuellebornii))),((((Hemiscorpius_subcinctus,Rhabdophis_caerulea),Pterocles_hodgsoni),Pseudorca_ornata),Melanocorypha_geniculata)),Philothamnus_marmorata),((((((Acipenser_flava,(((((((Allactaga_subglobosa,Squaterola_tetrix),Chalcides_naumanni),(Enhydra_deremensis,Erpeton_angustirostris)),(Milvus_ferruginea,Trapelus_gallicus)),Gerrhosaurus_troglodytes),((((((Anser_ferina,(Lagenorhynchus_leucocephala,(Neophron_montela,Remiz_politus))),(((((((Certhia_caesius,Dryobates_clypeatus),Uromastyx_hemionus),(Epicrates_cingulata,Nyctaalus_guentheri)),Mylopharyngodon_meles),Rhesus_infrafrenata),((((Dafila_aegagrus,((((((((Falcipennis_deminutus,(Phrynosoma_cavirostris,Scolopendra_purpurascens)),Monodon_leuconotus),(Minipterus_helvetica,(Ortigometra_avinivi,Remiz_dahurica))),Rhynchaspis_haliaetus),Hemiscorpius_collybitus),Rhynchophis_circia),Mesoplodon_musicus),Philomachus_citreola)),Nucifraga_ferrumequinum),Spizaetus_flavomaculatus),(Ketupa_unicolor,((Latastia_rubicola,Parnassius_maculatum),(Strepsilas_doctus,Thymallus_middendorffi))))),Pleurodeles_pica)),Notophthalmus_scutulata),Meles_semipalmatus),((Canis_ibis,(Lagenorhynchus_morinellus,Underwoodisaurus_uncia)),Rhabdophis_tarda)),Coregonus_heterolepidotus)),Ameiva_gallinago)),Bradypodion_pusilla),((Eubalaena_eremita,Querquedula_jaspidea),Nyctixalus_dominus)),Asthenodipsas_rufinus),Enhydris_thibetanus),((((Fuligula_cinereus,(Himantopus_cyanogenys,Leiurus_bengalensis)),Triturus_mackloti),Riparia_murinus),(Grampus_serricollis,Pelodiscus_ridibundus))),((((((((((((Aegialifes_botnica,Aegialites_arcticus),(Dryobates_colombianus,Pterocles_hispida)),Balaenoptera_maihensis),Eryx_pulchra),Androctonus_pictus),(Gypaetus_krueperi,Spalerosophis_leiosoma)),(Branta_indicus,Leiopython_vitulina)),(((Corvus_nigropalmatus,(Elseya_quadrivirgata,Ursus_riparia)),(Oceanodroma_horridum,Trionyx_parreyssi)),Lanius_fiber)),Sphenurus_multituberculatus),Canis_chrysaetus),Pelodytes_corone),Philomachus_armata));
Fuligula_cinereus Eubalaena_eremita

((Abantias_naumanni,(((Agama_ibis,Eremophila_tristis),Pterocles_rufina),((Cardiocranius_macqueni,(((((Charadrius_caudata,Nemorhaedus_sibirica),Rhacophorus_boyciana),(Chettussia_standingii,(Lanius_acutus,Paramesotriton_gallinago))),Nerodia_monilis),Pagophila_mexicana)),Mesoplodon_dulkeitiana))),Acheron_sujfunensis,(((((((((Aegialifes_sarasinorum,(Elaphe_melanuroides,((Streptopelia_mykiss,Tylototriton_physalus),Tropidurus_notaeus))),Pelusios_rhymnus),Apodora_indica),((Egretta_apollo,Pica_medici),(Lamprophis_hendricksoni,Procellaria_labiatus))),((Numenius_vertebralis,Physignathus_querquedula),Sphenops_querquedula)),Pica_horridum),(Phoca_aegyptia,Scincus_parreyssi)),(Ingerophrynus_linaria,Pelecanus_javanica)),((((((Alopex_bairdi,Balaenoptera_campestris),Milvus_porphyrio),(Fregilegus_ulikovskii,Rhombomys_battersbyi)),(Epipedobates_similis,Rhodostethia_dahurica)),(((((((Apalone_cioides,(Spalerosophis_crocodilus,Spermophilus_rufus)),Himantopus_fulva),Neophron_medirostris),Halichoerus_longipes),((((Aythya_subcinctus,(Epipedobates_chamaeleontinus,Plegadis_savignii)),((((Circaetus_graculus,Pedostibes_infrafrenata),Phrynohyas_bewickii),Sphenops_dives),Philacte_daurica)),(Pagophila_turtor,Ziphius_mutabilis)),Phasianus_alcinous)),Canis_grossmani),(Margaritifera_scincus,(Passer_gibbosus,Psalmopoeus_cyanea)))),((((Amphiuma_jaculus,(((((Arenaria_caudicinctus,(((((Argynnis_multituberculatus,Tiliqua_dauricus),Pelomedusa_giganteus),(Bufo_rufodorsata,Sceloporus_cocincinus)),Cyriopagopus_jubata),Petrocincla_fulva)),Tetraogallus_sieboldii),(((Emydura_sibilans,Hadrurus_proteus),Mabuya_gebleri),(Lamprophis_perrotetii,(Morelia_blakistoni,Seokia_meles)))),((Branta_nippon,(Parabuthus_kazanakowi,Scolopendra_cristata)),Hydrochelidon_fissipes)),(Holodactylus_ammon,((Monachus_smaragdina,(Phrynohyas_laevis,Recurvirostra_truncatus)),Odonthurus_clericalis)))),(((Chalcides_pelagicus,Hemiscorpius_alcinous),Liasis_caucasicus),(Erpeton_agama,Tropidurus_sibilans))),Enhydra_fuscatus),Minipterus_clypeata))));
Liasis_caucasicus Tropidurus_sibilans

((((((Acanthoceros_riparia,((Cuora_murinus,Gavia_novaeangliae),(((Leuciscus_dentata,Rhombomys_sp),Nhandu_martensi),Phasianus_melleri))),(Epipedobates_africanus,(Haliaetus_alpestris,Phrynops_dexter))),Chettussia_lehmanni),(Certhia_moschata,Cinclus_grandis)),((Bos_cavirostris,(Underwoodisaurus_avosetta,Zosterops_bobac)),Synthliboramphus_caudata)),((((((((((((((((Aegypius_trianguligerus,(Aplopeltura_barbata,Kaloula_albatrus)),Lamprophis_macrops),Anthropoides_auratus),(Chelus_hendersoni,Teratoscincus_fasciolata)),(Damon_brevipes,Pelusios_cinclus)),Ovis_campestris),((((((Cuora_leschenaultii,Nyctixalus_climacophora),Psammophis_resinifictrix),((Halichoerus_avinivi,((Latastia_sp,Mesoplodon_resinifictrix),Norops_celeber)),Homopholis_cliffordii)),sibiricus_morinellus),((Dyscophus_gibbosus,Ethmostigmus_equestris),Oedura_atriceps)),Pratincola_cyanus)),(((((Budytes_caudata,Fregilegus_eremita),Pogona_boyciana),((Cardiocranius_completus,Trachemys_novaeguineae),(Lycodon_geyri,Pterocles_pugnax))),((Emydura_prominanus,Varanus_modestus),Vormela_apollo)),Gavia_schneideri)),Gyps_amboinensis),Ruticilla_torquata),Holodactylus_atriceps),((Candoia_manul,Ptychozoon_emilia),Plethodon_breitensteini)),(Machetes_leucorodia,Polypedates_communis)),((Ceratophrys_guentheri,Gambelia_brandtii),(Cyclemys_chrysargos,Rhacophorus_caudata))),Ruticilla_sauritus),((((((((Argynnis_clarus,Damon_pedo),Spalax_caucasicus),Hadrurus_gebleri),Chlamydotis_scincus),(((Lutra_smaragdina,(Nemorhaedus_boyciana,Vulpanser_leiosoma)),Telescopus_melonotis),Pyxicephalus_ochropus)),Megaptera_dives),Ptyodactylus_marmoratus),((Cuon_nippon,Python_krueperi),Rissa_hosii))),(((Almo_emilia,Salvelinus_saiga),Anser_vanellus),Caiman_hemionus));
Phrynops_dexter Gyps_amboinensis

((Abantias_subniger,(Boiga_baibacina,(Hemiscorpius_anser,(((Heterodon_tinctorius,sibiricus_fuliginosus),Laudakia_carbonaria),Hydrochelidon_weliczkowskii)))),(((((((((((((((Acanthoceros_tetrix,(Hemiscorpius_stagnalis,Numenius_crucigera)),(Acanthosaura_lasiopterus,((Enhydris_semipalmatus,Philothamnus_erythronota),Melanocorypha_emarginatus))),Lycaenopsis_rosea),((Chrysemys_relictus,Rhamphiophis_hyperboreus),Python_keyzerlingii)),Eumeces_nivicola),(Chlidonias_flavigularis,Leptobrachium_perdix)),Pagophila_olivacea),(((((Accipiter_bobac,Cygnus_anser),((((Apalone_naumanni,Gazella_vermiculatus),Phelsuma_bimaculata),((Hydrosaurus_torquata,Opheodrys_scalaris),Limosa_cristatus)),Enhydris_hosii)),Morelia_murinus),Neolycaena_cavimanus),(Apalone_gallinago,Circaetus_monedula))),Passer_morinellus),((Dendrobates_salamandra,(Lepus_casualis,Neolycaena_collybitus)),Notophthalmus_lopatini)),(Cyriopagopus_apus,Lycodon_pica)),((Lampropeltis_thibetanus,Siniperca_mitratus),Paraphysa_tatarica)),Felis_marinus),Lyrurus_lobatus),Pachydactylus_serpentina),(((((((((Acanthogonatus_homeana,(Mareca_boa,Ziphius_caesius)),(Pyrrhocorax_carnifex,(Terpsihone_colchicus,Tetraogallus_vipio))),Aythya_blakistoni),(((Acanthogonatus_pictus,Kinosternon_emarginatus),((Bombus_pygargus,Salvelinus_parahybana),Ophisops_tanganicus)),((((((((((((Aegialifes_javanica,(Pelecanus_vittatus,Telescopus_interiorata)),((Androctonus_Bernicla,(Aphonopelma_caerulea,Cardiocranius_leucopsis)),Cottus_geyri)),Salvelinus_tigris),Picus_bifasciatus),Eucratoscelus_canagica),((Alcedo_zagrosensis,Theloderma_stellatum),(Charadrius_martensi,Pseudorca_castaneus))),Oligodon_fuliginosus),(Corvus_dahurica,Phasianus_galericulata)),Bombus_bicoloratum),Enhydris_kazanakowi),Emydura_carnivorus),Balaenoptera_calvus))),((Python_plathyrhychos,Sorex_cyanogaster),Salamandra_rostratus)),Argynnis_miliaris),(((((Bufo_not,(Pseudorca_carnifex,Sceloporus_altaicus)),Xenophrys_aegagrus),Spermophilus_citrsola),((Candoia_tenuirostris,Citellus_nivicola),(((Coenobita_scripta,Larus_multifasciata),Sericinus_helena),Hydrochelidon_femoralis))),Picus_lepturus)),(Ameiva_cinereus,Liasis_arizonensis)),Gecarcinus_avosetta));
Sericinus_helena Hydrosaurus_torquata

(Vipera_scalaris,Vanellus_doriae,Vanellus_ampullatus,Trapelus_lutris,Tiliqua_longicollis,Tetraogallus_cinaedus,Teratoscincus_botnica,Teratolepis_siebenrocki,Syrrhaptes_maldivarum,Spermophilus_virgo,Spalerosophis_baeri,Spalerosophis_armata,Sorex_uncia,Scaphiopus_radiata,Salvelinus_apus,Riparia_dominicus,Riparia_bairdii,Rhodostethia_relictus,Rhacodactylus_nigrolineatus,Rhacodactylus_maihensis,Rhabdophis_resinifictrix,Remiz_hyemalis,Pusa_daurica,Ptyodactylus_serricollis,Picus_brandtii,Physignathus_septentrionalis,Phelsuma_hypoleucus,Parus_cyanogaster,Pareas_boyciana,Pandinus_trianguligerus,Pachytriton_apollo,Pachydactylus_ladogensis,Otocoris_falcinellus,Otis_leiosoma,Ophisops_vulpes,Oceanodroma_cingulata,Nyctixalus_leucogaster,Nyctaalus_bonasus,Norops_monacha,Nhandu_notaeus,Netta_interiorata,Neophron_medirostris,Neolycaena_aspera,Mustela_oedicnemus,Meles_doctus,Megophrys_melanoleucus,Lycaenopsis_ammon,Limosa_kurilensis,Leiurus_rosea,Leiopython_tridactylum,Leiolepis_salamandra,Hirundo_durus,Hemitheconyx_himantopus,Hemitheconyx_alcinous,Gypaetus_ferina,Gonyosoma_dauricus,Gambelia_dubius,Falcipennis_citreola,Eudramias_coelestis,Eublepharis_livia,Eschrichtius_cavimanus,Epipedobates_politus,Epipedobates_elaphus,Epicrates_himantopus,Epicrates_grus,Dipsosaurus_campestris,Cygnopsis_flavigularis,Cuora_armata,Crocodylus_rubicola,Colaeus_cygnus,Circus_guttifer,Chondropython_tanganicus,Chlidonias_punctatus,Chlamydotis_pica,Chettussia_ichthyaetus,Carabus_galericulata,Capeila_resinifictrix,Caiman_cristata,Burhinus_walti,Budytes_battersbyi,Brachypelma_insignis,Bombyx_spaldingi,Bombus_geniculata,Aythya_carnifex,Asthenodipsas_ibera,Arenaria_wogura,Ardea_nupta,Apodora_lineatus,Anolis_grupus,Alloporus_corsac,Alcedo_mandarina,Alaus_cachinans,Alaus_argali,Aegialifes_javanica,Acipenser_virgo,Acipenser_moschata,Acanthogonatus_moschiferus)Xenophrys_calamita;
Pachytriton_apollo Eudramias_coelestis

((((((((((((Accipiter_martensi,(Archispirostreptus_caniceps,Saiga_epops)),(((((Hottentotta_spaldingi,(Marmota_dulkeitiana,Megaloperdix_edulis)),Phalaropus_linaria),Net_adamsii),Saxicola_maculatum),Rhesus_margaritifera)),Tetrao_viridescens),Pandion_horridum),Budytes_vegans),Mochlus_cyanogenys),Alopex_crucigera),Passer_cyanogenys),(Buthacus_colombianus,Seokia_pusilla)),Pedostibes_ridibundus),Osmoderma_medici),((((((Alauda_valliceps,((Aphonopelma_erythropus,Pelecanus_laticauda),Gonyosoma_shadini)),(((Argynnis_perdix,Lamprolepis_decorus),Rhacodactylus_similis),((((Bos_turtor,Eumeces_cyanogenys),(Myotis_emilia,(Plegadis_punctatus,Psammophis_euptilura))),Phormictopus_pulcher),((Citharacanthus_hirundo,Phoca_torquata),Tadarida_sieboldii)))),(Egretta_serpentina,(Fuligula_alterna,Gyps_cinerea))),((Atrophaneura_communis,Geochelone_Jankowskii),(((Brachyramphus_trigonopodus,Gecarcinus_ornata),(Chlamydosaurus_subcinctus,Triturus_durus)),(Geochelone_calligaster,Lystrophis_fuscus)))),Ptyodactylus_versicolor),(Grus_coloratovillosum,((Hottentotta_ciliatus,Pterocles_ovata),Tryngites_scripta))),(((((((((((Alaus_galericulata,Machetes_rhymnus),(((Alcedo_krueperi,Uncia_korschun),Arctomys_tarandus),Cottus_bengkuluensis)),Monodon_diadema),(((Anthropoidae_fluviatilis,Nyctaalus_dispar),Oceanodroma_trigonopodus),(((((((Cyclemys_anatina,Micropalama_rubicola),Hydrosaurus_torquata),((Glareola_cyanea,Pachytriton_eburnea),Rhombomys_mykiss)),Glareola_temminskii),Tylototriton_himantopus),Strepsilas_atthis),Tamias_regius))),(Kinixys_nigra,Phormictopus_scincoides)),((Aquila_jacksoni,((((Bronchocela_deminutus,((Certhia_obsoleta,(((Leiolepis_rutila,Oedura_pachypus),Tadorna_gemmicincta),Natriciteres_bewickii)),Cyclemys_fragrans)),Phalaropus_vegans),Clemmys_floridana),Siniperca_fernandi)),(Cardiocranius_melonotis,Scincus_chamaeleontinus))),(Eulabeia_geniculata,Middendorffinaia_prasina)),(Fregilegus_fasciata,(Lanius_smaragdina,Teratoscincus_Anas))),(((Argynnis_insularis,Monachus_hendricksoni),Nhandu_javanica),Otis_jubata)),(Alaus_tatarica,(Bradypterus_physalus,Mogera_relictus))),Platemys_monachus));
Myotis_emilia Anthropoidae_fluviatilis

((Acanthogonatus_jubata,(Bronchocela_atriceps,Cuon_subglobosa)),((((((((((((Aegialifes_terrestris,((Ctenotus_scutulata,Underwoodisaurus_terrestris),(Leuciscus_caelebs,Netta_kopsteini))),(Philacte_rubida,Vanellus_pedo)),Buthus_holbrooki),(Lycodon_hilarii,Lyrurus_graeca)),(Buteo_dignus,Lepus_physalus)),(((((Allactaga_guentheri,Chlamydosaurus_grossmani),Canis_mugodjaricus),(Meles_cingulata,Rangifer_altaica)),((((Leiurus_plumifrons,crecca_monachus),Mareca_caeruleus),((Megaptera_fuliginosus,(((Pachydactylus_himantopus,Tamias_melanuroides),Podoces_gobio),sibiricus_leporosum)),(Phrynohyas_garullus,Rhodostethia_versicolor))),Odonthurus_obsoleta)),Eurynorhynchus_situla)),(((Bradypodion_truncatus,Dryobates_guentheri),Sceloporus_brandtii),((Heteroscodra_coloratovillosum,(Hydrosaurus_thibetanus,Otocoris_alterna)),(((Megophrys_latiscutatus,Neolycaena_taczanowskius),Otis_mexicanum),Polypedates_virgo)))),((Callipogon_siebenrocki,Paradoxornis_fuscus),Camptoloma_bedriagai)),Pseudemys_relictus),Ambystoma_stimsoni),((Damon_javanica,(Eudrornias_taezanowskyi,Scaphiopus_piscator)),(Micropalama_variabilis,Tylototriton_torquatus))),((((((Alectoris_similis,((Osteopilus_guineti,Pseudemys_fulvus),Sorex_japonica)),Oxyura_arseniavi),((((((Anolis_sepsoides,Nucifraga_emarginatus),Antaresia_scutulata),(((Enhudra_virgo,Ovis_tarandus),Paraphysa_ornata),Perdix_eximia)),Bos_glacialis),Ptychozoon_niloticus),Kaloula_glaucescens)),((((((((((Athene_albocinctus,(Emydura_parahybana,Eryx_iguana)),Phrynomerus_carinatus),Gyps_sarasinorum),Callipogon_hassanica),((Cyriopagopus_odoratus,Ephibolus_duplus),Teratoscincus_dennysii)),Remiz_papuana),Eudrornias_serricollis),Opheodrys_standingii),Nyroca_maritimus),Aythia_viridis)),Ceratophrys_rufus),Burhinus_alpinus)),(((((Alectoris_merganser,Pica_javanica),(Ethmostigmus_zonata,(Monticola_marmorata,Philothamnus_leucophyllata))),crecca_kazanakowi),Rosalia_heliaca),((Chlamydotis_dignus,Philothamnus_leucogaster),Teratoscincus_lineatus)));
Acanthogonatus_jubata Pseudemys_relictus

((((((((((((Aegypius_tetrax,((Athene_horridum,Zosterops_longicaudata),(Crocodylus_tridactylum,Hirundo_pulchra))),(Clemmys_duplus,Liasis_himalayensis)),((((((((((((Apodora_serricollis,Asthenodipsas_leucomystax),Ctenotus_madagascariensis),Bombus_geyri),Heterodon_daurica),Otocoris_nigra),Nerodia_bairdi),(Aythya_subniger,(Kinixys_sibirica,((Micropalama_subniger,Spermophilus_albocinctus),Ptyodactylus_vermiculatus)))),Litoria_lutris),Eutamias_aegyptia),Bradypodion_blakistoni),((Arenaria_hilarii,Rosalia_pusilla),Melanocorypha_crassidens)),Caiman_variabilis)),(((((Avicularia_aleutica,Netta_mykiss),Sceloporus_albigula),((Testudo_milii,Vanellus_caudata),Vanellus_insignis)),Gonyosoma_mlokosiewiczi),Sus_hardwickii)),(((Antaresia_scrofa,(((((((Balaenoptera_maldivarum,(((Calotes_azureus,Tadorna_davidiana),Eumeces_stimsoni),Emberiza_teguixin)),((Bronchocela_hypoleucus,Dyscophus_pardalis),Mergus_tinctorius)),Castor_pelagicus),Neolycaena_pygmeus),(Gongylophis_gallinago,Tamias_arenarius)),Lutra_dominus),Capra_sieboldii)),((((((((Basiliscus_vanellus,Oligodon_cyanochloris),Dendrelaphis_carbo),(Mesoplodon_ferruginea,Morelia_pictus)),(Ctenotus_decorus,(Lamprolepis_capreolus,Spermophilus_platyrhinos))),((((Charadrius_rupestris,Varanus_casualis),Lyrurus_mandarina),Rhacophorus_placidus),Oligodon_kurilensis)),Totanus_lopatini),Lepidobatrachus_riparia),Mareca_falcinellus)),((((((Aythia_pardus,((Cygnopsis_virgo,(Milvus_pugnax,Pusa_parahybana)),Marmota_graeca)),(Salvelinus_gebleri,Siniperca_chuatsi)),Odobenus_fuscatus),Leiolepis_taeniura),Notophthalmus_cristatella),Chrttusia_guttata))),(Aphonopelma_salvator,Apus_scrofa)),Phalacrocorax_tadorna),(Ardea_catenifer,Petrocincla_verrucosus)),Citellus_niloticus),Heterodon_Anas),((((Chen_rufina,Phoca_exquisita),(Myotis_hyperboreus,Sternotherus_glareola)),Lagenorhynchus_colubrinus),Megophrys_hipposideros)),(Allobates_metallica,Limosa_labiatus),Alopex_nipalensis);
Mareca_falcinellus Gonyosoma_mlokosiewiczi

((((((((Acipenser_exquisita,(Clemmys_linaria,Turdus_rubida)),Scaphiopus_macqueni),((Gavia_lepturus,Middendorffinaia_sp),Lycaenopsis_cavimanus)),((Calidris_bewickii,((Coleonyx_madagascariensis,Heterodon_ammon),Natriciteres_quinquetaeniata)),Capella_limosa)),Trapelus_chinensis),(Avicularia_brevirostris,Himantopus_papuana)),Alopex_labiatus),(((((((((((Aegialites_scabra,Camptoloma_scincoides),((((Bradypterus_dactylisonans,Dyscophus_bicoloratum),Hyperoodon_apollo),Paraphysa_ampullatus),Vulpanser_onocrotalus)),((((Circus_govinda,Ortigometra_asperum),Rissa_blythi),Odobenus_epops),Tamias_imperator)),(Butastur_canagica,Gecarcinus_dendrophila)),Haliaeetus_licin),((((Ambystoma_citreola,Ketupa_flavomaculatus),((Limnaeus_angulifer,Micropalama_imperator),Sternotherus_naumanni)),Eumeces_nasuta),((((((((Anthropoidae_schneideri,Xenophrys_sudanensis),Megaloperdix_collaris),((Cuon_ferrumequinum,Phrynosoma_cyanogenys),Pagophila_geyri)),Hydrochelidon_fischeri),(Chamaeleo_corone,Phormictopus_monilis)),Pica_aspera),(Dryobates_barbatus,Uncia_interiorata)),Sitta_czerskii))),(((((((Brachyramphus_subminiatus,Capeila_carnifex),(Pica_acanthinura,Ziphius_subniger)),Triturus_dispar),((Megaptera_not,Pituophis_pallidus),Nhandu_japonensis)),(((Capeila_brevipes,Cypselus_sp),Glareola_cepediana),Testudo_galericulata)),Eulabeia_nyroca),(Certhia_spilota,Ciconia_hardwickii))),Margaritifera_quinquestriatus),((((Allactaga_lopatini,(Chelodina_clarus,Crocodylus_marcianus)),((Crotaphytus_rufinus,Hydrosaurus_ochropus),Odobenus_boulengeri)),Buthacus_grunniens),Cyclemys_franckii)),(Epipedobates_viridescens,Rangifer_gecko)),((Capella_aestivus,(Charadrius_atthis,Paradoxornis_godlewskii)),Halichoerus_scabra)),((Aegypius_colubrinus,Hysterocrates_daurica),(Buthacus_bedriagai,(Dipus_caucasicus,Iomachus_cyanea))));
Halichoerus_scabra Crotaphytus_rufinus

((((((((((Alectoris_bengalensis,Xenophrys_rufodorsata),Dendrelaphis_caeruleus),Dendrelaphis_eximia),((Argynnis_resinifictrix,Gekko_arenarius),Gecarcinus_molurus)),((Corallus_leucoptera,Seokia_hemionus),Norops_alpestris)),(Buthacus_garmani,Uncia_porphyrio)),Latastia_querquedula),Notophthalmus_lepturus),(((((((((Avicularia_cinclus,(((((((((((Coturnix_longipes,Varanus_monacha),(((Equus_botnica,Plegadis_himalayanus),Sus_boa),Mochlus_serricollis)),(Glareola_naumanni,Heteroscodra_baibacina)),Egretta_daurica),Platemys_grandis),((Himantopus_eximia,Querquedula_temminskii),(Psammophis_parvus,Thymallus_leucostomum))),Gerrhosaurus_bengalensis),Gonocephalus_carbonaria),((Ninox_difficilis,Ruticilla_hardwickii),Rosalia_kurilensis)),(((Dahurinaia_microlepis,((Equus_variegatus,Uncia_japonica),Tadorna_borealis)),Saxicola_zagrosensis),(Rissa_verrucosus,Rufibrenta_ussuriensis))),(Egretta_quinquetaeniata,Euspiza_middendorffi))),(Falco_ussuriensis,(Larus_glacialis,Lystrophis_sagrei))),(Ctenosaura_agama,Natriciteres_moschiferus)),Buthus_walti),Dahurinaia_smithi),Candoia_gobio),((Capra_rosea,(Citharacanthus_caniceps,Squaterola_similis)),Podoces_vitulina)),((Laudakia_armeniacus,Teratoscincus_clinatus),Petrocincla_rudicolis)),Pogona_deminutus)),(Alpes_murinus,((((((((Bombina_strepera,(((Bufo_musicus,((Epicrates_oxycephalum,Myotis_leucopsis),Eudramias_grupus)),((Eirenis_mystacinus,Paraphysa_spaldingi),Leiocephalus_maculata)),(Eucratoscelus_caucasicus,Hottentotta_ladogensis))),(Dafila_kingii,Pelusios_heterolepidotus)),(Lamprolepis_exquisita,Mogera_enydris)),Spalerosophis_deserti),((Bubulcus_helena,Buteo_lavaretus),Ophisops_lehmanni)),(((Callipogon_coloratovillosum,Eremophila_relictus),Osmoderma_bukhunensis),((Casarca_tristis,Kinosternon_borealis),Falcipennis_monacha))),(Scolopax_orientalis,Tringa_kopsteini)),Trachemys_mongolica)),Anas_atra);
Larus_glacialis Gonocephalus_carbonaria
'''

    values = data.split()
    result = []
    for i in range(len(values)//3):
        nwck = NWCK(values[i*3],values[i*3+1],values[i*3+2])
        result.append(nwck.distance_between_nodes)
    print(*result)

if __name__ == '__main__':
    Main()