#Matt Person
#Rosalind Problem: PRTM
#source
'''Given: A protein string P of length at most 1000 aa.
Return: The total weight of P. Consult the monoisotopic mass table.'''

import sys

sys.path.insert(0,'C:\\Users\\Matthew\\Desktop\\Python Projects\\Rosalind\\')

from RUtils.src.RosalindUtilities import RosalindUtilities

class PRTM:
    def __init__(self,P):
        self.ru = RosalindUtilities()
        self.weight = self.get_protein_monoisotropic_weight(P)

    def get_aa_monoisotropic_weight(self,aa):
        return self.ru.monoisotropic_mass_by_aa_code[aa]

    def get_protein_monoisotropic_weight(self,P):
        return round(sum([self.get_aa_monoisotropic_weight(aa) for aa in P]),3)

def Main():
    P = 'YSDSPPGAMRFPPSASPYHTVEYWYRNLWRECPAMVKWIVKKMDRGDSAVFNDHPIEYKTTLGIAENFDCCPWSFRILDKAYHSPLDEAVDAMNLRQCHATQCCPGRAFMWMCPQDECGKMSRGRKVMNSLTWMDVRPAAKGQHCWAFLCFVMYVCGLKRKTETPTRSKRLQIKVYFVGLAQPRSDDHPYQISWWEPEATKNNMFMCFAQGRPQPGKDGLWKFLIGFAQMVMMDRQHIGWQCLEPVCSSRDVAIARACENSWVHWPYKVRNFQKTTKDQFWRKARVTDWAELPGLLGAPPKDEFEMPYLNDRTIKPEFGHGDHHKHYVMHFSFHQNCRDEDMVFTAWSLKAVNPNTDIAHIKGNNGVVTNEHPKYSSSKFSDPFWQRYLVQNDLMFRPCHPYYHMEDPRQYVTPKEARYNHYDRLEFKWVVTSQKGMASKYMRCHTACKPPFFHQELAALDWYTAWKEGHEHLLVIKGCNMKNIHMPCKINVQQCQRLMPPHGQCGWRTPLFQCTWAHLPFVSSFSANMVIGYSGATHGRLTKMFPRKRSKTNITMGSGVWKHASARPESWGIAKFLGFLQTSWPSFWSTQHHCGSMCKGGPGGKQNLKVLPQSHPLLQQPHTLYMQWTPHHWKKVWFYIVLCAMQEKVHELHCDVFLIGVRVWAFRYHQTHGVNHEHHYNPLTFRLMVGPDMTHMYVHLIHVDICHWACLDSDGDKEGTGPARFAIYTQQTMMSRNNQWCSTVYYGLYKEFCDCRLIACWTNCCVLNQCWDTTTEQDWPKAYRQRMQMWPGFCFNATHAYFAWFHIPKPVRTFSPCANHLFNPDTEPMNNSWWETMVADFFQWRAQLSHSAWMSHTMTVRHIYKDRVPRYDDWQPPPLTWWAIVWELLAALAECRGHVAQYHRHQPDMVRQYWLWANNENASQKEMTMSNSLVWIHYMWDSSNVLFRYAKHIGTLF'
    prtm = PRTM(P)
    print(prtm.weight)

if __name__ == '__main__':
    Main()