import sys

sys.path.insert(0,'C:\\Users\\Matthew\\Desktop\\Python Projects\\Rosalind\\')

from RUtils.src.RosalindUtilities import RosalindUtilities

class PRTM:
    def __init__(self):
        self.ru = RosalindUtilities()

    def get_aa_monoisotropic_weight(self,aa):
        return self.ru.monoisotropic_mass_by_aa_code[aa]

    def get_protein_monoisotropic_weight(self,P):
        return round(sum([self.get_aa_monoisotropic_weight(aa) for aa in P]),3)

def Main():
    prtm = PRTM()
    P = 'YSDSPPGAMRFPPSASPYHTVEYWYRNLWRECPAMVKWIVKKMDRGDSAVFNDHPIEYKTTLGIAENFDCCPWSFRILDKAYHSPLDEAVDAMNLRQCHATQCCPGRAFMWMCPQDECGKMSRGRKVMNSLTWMDVRPAAKGQHCWAFLCFVMYVCGLKRKTETPTRSKRLQIKVYFVGLAQPRSDDHPYQISWWEPEATKNNMFMCFAQGRPQPGKDGLWKFLIGFAQMVMMDRQHIGWQCLEPVCSSRDVAIARACENSWVHWPYKVRNFQKTTKDQFWRKARVTDWAELPGLLGAPPKDEFEMPYLNDRTIKPEFGHGDHHKHYVMHFSFHQNCRDEDMVFTAWSLKAVNPNTDIAHIKGNNGVVTNEHPKYSSSKFSDPFWQRYLVQNDLMFRPCHPYYHMEDPRQYVTPKEARYNHYDRLEFKWVVTSQKGMASKYMRCHTACKPPFFHQELAALDWYTAWKEGHEHLLVIKGCNMKNIHMPCKINVQQCQRLMPPHGQCGWRTPLFQCTWAHLPFVSSFSANMVIGYSGATHGRLTKMFPRKRSKTNITMGSGVWKHASARPESWGIAKFLGFLQTSWPSFWSTQHHCGSMCKGGPGGKQNLKVLPQSHPLLQQPHTLYMQWTPHHWKKVWFYIVLCAMQEKVHELHCDVFLIGVRVWAFRYHQTHGVNHEHHYNPLTFRLMVGPDMTHMYVHLIHVDICHWACLDSDGDKEGTGPARFAIYTQQTMMSRNNQWCSTVYYGLYKEFCDCRLIACWTNCCVLNQCWDTTTEQDWPKAYRQRMQMWPGFCFNATHAYFAWFHIPKPVRTFSPCANHLFNPDTEPMNNSWWETMVADFFQWRAQLSHSAWMSHTMTVRHIYKDRVPRYDDWQPPPLTWWAIVWELLAALAECRGHVAQYHRHQPDMVRQYWLWANNENASQKEMTMSNSLVWIHYMWDSSNVLFRYAKHIGTLF'
    print(prtm.get_protein_monoisotropic_weight(P))

if __name__ == '__main__':
    Main()