#Matt Person
#Rosalind Problem: RNA
#source
'''Given: A DNA string tt having length at most 1000 nt.
Return: The transcribed RNA string of  t'''

class RNA:
    def __init__(self,t):
        self.transcription = self.transcribe(t)


    def replaceTWithU(self,inputString):
        return inputString.replace('T','U')

    def transcribe(self,inputString):
        return self.replaceTWithU(inputString)

def main():
    inputString = 'GATTAATCCGCTCGCAGGGACGCTCTATCTGACAAAAGCACGAGACATATGGTCCAGACTCCTCGCACATTGTAGCCTCGATCCCTGAGAAGTTGTTTCCTTCCCAATATCTGTAGATCTTGCCCGGCACAAGGAAAATGTGGTGCTCACCGTCTAGGTGAATTGTAAAGGACTTCGGCGATACCTTGAGTTTGTCAAGCGTGGGTGGGTAAATTGTTCCGCTTCATCCTTGCGTGCTAGATTAATCAGCTAACTGGTACGGGATCACGCCTTGCCGTTGCACACCGGCACCCAGCTGGACAGCGACAATTGGGGCAAGAAAGCTTGCTCTATGGTTCAGATATGCGCTTATTTACTGCGGAGAGTGGTCACATGGACCCACCTGGGGCTGCTAGAGTCTCGATCTGCAACACAAGTCTTTGATTGCGCAGGTGATCTCGTGACCCCAATCAGACCCAGGCGCCGATTATTAACAGCGACTCGCAAGATTAGCCCTCAACTCGTCTTCCCTGGTGGACATGATGATTTGAGTACGTCCATGCATTAAGCTAATAGCCCAATGGTGGAGGCACTCCAGAGGATGCAGATGGCCCCCCGGGAATCCTGTCCTAGGCAGTACTTATCTCCCCCGAGATGGCGATAATCGCGCTGCACCGCGATCCACTTCCAATCGCTACCGGCTCGGGTTAGCGCGCAGTTCGTCCGGCAGTTATCTGCGAGAATCTTTCTGCATACAGTGCTTTCAGCGGTCCTGGATTTTCCTTAACCGTCAGCCCTCACCATTCGCCATAGCAAGCCTCGGGATAATTTACACATCTTGTACACCAATGCTAACGCAACCCATACCAGGGAACATTTGGCCTTCCGAAAAGCAAGCGTAGTTGTCTGACACTTTATGATGGAGTCACAACCGGTGATGAACTAAATCGTGGGTCACTGCCGGTCCAGTGTCGAGCGCTGGCAGCATAAACGCACAACTCAGTTCGAACCTAGAGGT'
    transcript = RNA(inputString)
    print(transcript.transcription)

if __name__ == "__main__":
    main()