import unittest

from ..MPRT import MPRT

class TestPRTM(unittest.TestCase):
    def setUp(self):
        self.mprt = MPRT()

    def test_get_FASTA_for_uniprotid(self):
        self.assertEqual(self.mprt.get_FASTA_for_uniprotid('A2Z669'),
                                          '''>sp|A2Z669|CSPLT_ORYSI CASP-like protein 5A2 OS=Oryza sativa subsp. indica GN=OsI_33147 PE=3 SV=1
MRASRPVVHPVEAPPPAALAVAAAAVAVEAGVGAGGGAAAHGGENAQPRGVRMKDPPGAP
GTPGGLGLRLVQAFFAAAALAVMASTDDFPSVSAFCYLVAAAILQCLWSLSLAVVDIYAL
LVKRSLRNPQAVCIFTIGDGITGTLTLGAACASAGITVLIGNDLNICANNHCASFETATA
MAFISWFALAPSCVLNFWSMASR\n''')

    def test_get_protein_string_for_uniprotid(self):
        self.assertEqual(self.mprt.get_protein_string_for_uniprotid('A2Z669'),
                         '''MRASRPVVHPVEAPPPAALAVAAAAVAVEAGVGAGGGAAAHGGENAQPRGVRMKDPPGAPGTPGGLGLRLVQAFFAAAALAVMASTDDFPSVSAFCYLVAAAILQCLWSLSLAVVDIYALLVKRSLRNPQAVCIFTIGDGITGTLTLGAACASAGITVLIGNDLNICANNHCASFETATAMAFISWFALAPSCVLNFWSMASR''')

    def test_get_locations_for_motif_in_protein(self):
        motif = 'N[^P][ST][^P]'
        protein = 'MKNKFKTQEELVNHLKTVGFVFANSEIYNGLANAWDYGPLGVLLKNNLKNLWWKEFVTKQKDVVGLDSAIILNPLVWKASGHLDNFSDPLIDCKNCKARYRADKLIESFDENIHIAENSSNEEFAKVLNDYEISCPTCKQFNWTEIRHFNLMFKTYQGVIEDAKNVVYLRPETAQGIFVNFKNVQRSMRLHLPFGIAQIGKSFRNEITPGNFIFRTREFEQMEIEFFLKEESAYDIFDKYLNQIENWLVSACGLSLNNLRKHEHPKEELSHYSKKTIDFEYNFLHGFSELYGIAYRTNYDLSVHMNLSKKDLTYFDEQTKEKYVPHVIEPSVGVERLLYAILTEATFIEKLENDDERILMDLKYDLAPYKIAVMPLVNKLKDKAEEIYGKILDLNISATFDNSGSIGKRYRRQDAIGTIYCLTIDFDSLDDQQDPSFTIRERNSMAQKRIKLSELPLYLNQKAHEDFQRQCQK'
        self.assertEqual(self.mprt.get_locations_for_motif_in_protein(motif,protein),[85,118,142,306,395])
        protein = 'MRASRPVVHPVEAPPPAALAVAAAAVAVEAGVGAGGGAAAHGGENAQPRGVRMKDPPGAPGTPGGLGLRLVQAFFAAAALAVMASTDDFPSVSAFCYLVAAAILQCLWSLSLAVVDIYALLVKRSLRNPQAVCIFTIGDGITGTLTLGAACASAGITVLIGNDLNICANNHCASFETATAMAFISWFALAPSCVLNFWSMASR'
        self.assertEqual(self.mprt.get_locations_for_motif_in_protein(motif, protein), [])

    def test_get_locations_for_motif_in_uniprotid_list(self):
        motif = 'N[^P][ST][^P]'
        protein_list = '''A2Z669
B5ZC00
P07204_TRBM_HUMAN
P20840_SAG1_YEAST'''.split('\n')
        expected = [('B5ZC00', '[85, 118, 142, 306, 395]'), ('P07204_TRBM_HUMAN', '[47, 115, 116, 382, 409]'), ('P20840_SAG1_YEAST', '[79, 109, 135, 248, 306, 348, 364, 402, 485, 501, 614]')]
        self.assertEqual(self.mprt.get_locations_for_motif_in_uniprotid_list(motif,protein_list),expected)