from collections import Counter

class CountNucleotides:
    def __init__(self):
        pass

    def create_counter(self,input):
        return Counter(input)

    def count_nucleotides(self,input):
        c = self.create_counter(input)
        return [c['A'],c['C'],c['G'],c['T']]

def main():
    input = 'AAAACGTATAGAAACGAGTCCAAAATAAGAGTTCGGTGATACCCATGCGGAGCTGCTGTCATATGGTTCCCTCACTTCCTACTAGATGAAAACCGTGGACATACGCAACGTGATCCCCCTGGATAACCCAAACTTAGCGGTCAGCTCCGACGGCGCACCTCAGTTGTATTCTGCGGATAAGTTTCGAAACTACTACCATTGATCCTTGCTGATGACAAGCAGCGTTTTATGATTCATGGTACTGGGGAAGCGAGAGCGTCGACCGGACAATCACACTAAACTTTCGCTGAAAACTAAGACTACCCTTAAGTCCACAGTCTATAGTAGTTAATCACGCTCCTACTAGTCGGCAGGCTTAACAAAGACGTGATCGGGCTGGCTGATGACTCCCAGTCCTCCTGCCAGCTGCGGGACAACGGCCAACATTTCGCAGTTTACTTGGTCCCGCCCGACATCTCGGGATTAAAACCAAACCCAAAAAGTTTTAACCGTCCGGGGCGTCAAGTGTCGGCGTAACAATAGACCAGGTACCCGCGTCACAGTCAAGTTCTTAAGCAATTGACACGTCCCACGTACTTGGATCGCGTTCAAACACGTCGAATGGGTGCTGCGACCGGCAGCATCGAATTATAACAATAAGAGCACAAGATCCCGTGAACCGTTTACGTTGCCTGTGAAAAGGTAGGACGCCGAATTCATGTAGTCGGTATAGTTATATCTTCCGGGAAAATATTATCGCTAAGATCGCATCCCCGAAAGATGTTGATTGGGAGGCACCCCCTACTCATCGCAGAAATCGATCTATTGCTGCTAAAACTAATGATACAGCAGATCCTGGGTTGAGTGCACATCTGGGACTGTATGAGGAATGTGTACCCTCGCCT'
    counter = CountNucleotides()
    print(*CountNucleotides.count_nucleotides(counter,input))

if __name__ == '__main__':
    main()
