from functools import reduce
import operator
import sys

sys.path.insert(0,'C:\\Users\\Matthew\\Desktop\\Python Projects\\Rosalind\\')

from RUtils.src.RosalindUtilities import RosalindUtilities


class MRNA:
    def __init__(self):
        self.ru = RosalindUtilities()

    def get_count_codons_for_amino_acids(self,amino_acid):
        return(len(self.ru.codons_for_amino_acid_codes[amino_acid]))

    def get_number_possible_RNA(self,protein):
        return reduce(operator.mul,[self.get_count_codons_for_amino_acids(aa) for aa in protein],self.get_count_codons_for_amino_acids('Stop')) % 1000000


def Main():
    mrna = MRNA()
    protein = 'MESLERCGKCQHTQGGILHSKSQNLTTNWGWDYLLDNRIDQMWMPTDWFTDFQEMSRQATEEVGHYCCHSRTKRMWAMHHDTFNWPKIDPERMADLRIYIACIHNRMQCLVLPYASSDMNARSDLQCPAAIRRQLFVWKSDIYVSRLDFMRFMNNEHHFTKFIPSWMCPNHPHTTSLYHQKMWNSMKFAIEQNRVVHGINRSGDQRTAPYGKCGIDIQQCKKKCLAFRHNFDHWQAYHDSKLGWSIKHFTIENIDYHSAQYWTRARDHHNESDTCKKCNERIMVCTHGCCFQFNMSLRKVEHEQLAGIIKAKYWYNENDKKKYRKGLELRDPYDNWSVTKPCCWGNIKFWKSPSHPETYCYAYIIVDMVQYFGTHEMTWFEFPSNNYQDHFQETRSPSNTKSQAANRRWQSWQEPMSIDAIQVVGNGVLNHFCYIPRDTYHVKAPSQDDNPHDSMPMLHMFEARVWWCYEHMLFSDEGQDTTMWTISTTDNQATGPDTMDVQITGRFEGCCKMNDVKVLHRDQLKFYAIWAMMVHFKGMYAWEGWFIPFYNTYTKIEISVDNDDHHVWHNLMTKTQVNSEQIFCRDDEFFNHINDKLQQASDIWNSNTWGWWKRFRDMCVCNWGPKMDHGCCTAFLAEIHTQQGHFLQICRSCMAIWKETSSYWGDDMWHAWRFQMITYMNQQLYTMQHEKSDFIPNNRHTWTSFIYQTHTLVSHCSMQGQCQVWDYIELHRPPHWMCVNNWTYRSMLSDCQEHSESTVVCTARYKINAHAKGHWPKKHGDDSWDDINIVVWPGWNPQTGNNYTAMWGFNWARDMRHIAVRKLAEQVLWHSTMIIKGNMSATWCNDQNIDHFTPAGDVIDMKSHVWHCVAALREIYTSWNHIWDRLEHKPHDHFTQNCPHSYPRQWGTSHLEVGARCPQADREMISIKPYHIYNKQTWPMQHPYIMACYPCHRQTKYCQGVGHYEPDVSWQWGKCLGGPIFGHYSEYEGWPMDGKVL'
    print(mrna.get_number_possible_RNA(protein))

if __name__ == '__main__':
    Main()