#Matt Person
#Rosalind Problem: MRNA
#source
'''Given: A protein string of length at most 1000 aa.
Return: The total number of different RNA strings from which the protein could have been translated, modulo 1,000,000.
(Don't neglect the importance of the stop codon in protein translation.)'''

from functools import reduce
import operator
import sys

sys.path.insert(0,'C:\\Users\\Matthew\\Desktop\\Python Projects\\Rosalind\\')

from RUtils.src.RosalindUtilities import RosalindUtilities


class MRNA:
    def __init__(self,protein_string):
        self.ru = RosalindUtilities()
        self.num_different_RNA_strings = self.get_number_possible_RNA(protein_string)

    def get_count_codons_for_amino_acids(self,amino_acid):
        return(len(self.ru.codons_for_amino_acid_codes[amino_acid]))

    def get_number_possible_RNA(self,protein):
        return reduce(operator.mul,[self.get_count_codons_for_amino_acids(aa) for aa in protein],self.get_count_codons_for_amino_acids('Stop')) % 1000000


def Main():
    protein = 'MESLERCGKCQHTQGGILHSKSQNLTTNWGWDYLLDNRIDQMWMPTDWFTDFQEMSRQATEEVGHYCCHSRTKRMWAMHHDTFNWPKIDPERMADLRIYIACIHNRMQCLVLPYASSDMNARSDLQCPAAIRRQLFVWKSDIYVSRLDFMRFMNNEHHFTKFIPSWMCPNHPHTTSLYHQKMWNSMKFAIEQNRVVHGINRSGDQRTAPYGKCGIDIQQCKKKCLAFRHNFDHWQAYHDSKLGWSIKHFTIENIDYHSAQYWTRARDHHNESDTCKKCNERIMVCTHGCCFQFNMSLRKVEHEQLAGIIKAKYWYNENDKKKYRKGLELRDPYDNWSVTKPCCWGNIKFWKSPSHPETYCYAYIIVDMVQYFGTHEMTWFEFPSNNYQDHFQETRSPSNTKSQAANRRWQSWQEPMSIDAIQVVGNGVLNHFCYIPRDTYHVKAPSQDDNPHDSMPMLHMFEARVWWCYEHMLFSDEGQDTTMWTISTTDNQATGPDTMDVQITGRFEGCCKMNDVKVLHRDQLKFYAIWAMMVHFKGMYAWEGWFIPFYNTYTKIEISVDNDDHHVWHNLMTKTQVNSEQIFCRDDEFFNHINDKLQQASDIWNSNTWGWWKRFRDMCVCNWGPKMDHGCCTAFLAEIHTQQGHFLQICRSCMAIWKETSSYWGDDMWHAWRFQMITYMNQQLYTMQHEKSDFIPNNRHTWTSFIYQTHTLVSHCSMQGQCQVWDYIELHRPPHWMCVNNWTYRSMLSDCQEHSESTVVCTARYKINAHAKGHWPKKHGDDSWDDINIVVWPGWNPQTGNNYTAMWGFNWARDMRHIAVRKLAEQVLWHSTMIIKGNMSATWCNDQNIDHFTPAGDVIDMKSHVWHCVAALREIYTSWNHIWDRLEHKPHDHFTQNCPHSYPRQWGTSHLEVGARCPQADREMISIKPYHIYNKQTWPMQHPYIMACYPCHRQTKYCQGVGHYEPDVSWQWGKCLGGPIFGHYSEYEGWPMDGKVL'
    mrna = MRNA(protein)
    print(mrna.num_different_RNA_strings)

if __name__ == '__main__':
    Main()