#Matt Person
#Rosalind Problem: DNA
#source
'''Given: A DNA string ss of length at most 1000 nt.
Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in ss.'''

from collections import Counter

class DNA:
    def __init__(self,s):
        self.s = s
        self.nucleotide_count = self.count_nucleotides()

    def create_counter(self,input):
        return Counter(input)

    def count_nucleotides(self):
        c = self.create_counter(self.s)
        return [c['A'],c['C'],c['G'],c['T']]

def main():
    input = 'AAAACGTATAGAAACGAGTCCAAAATAAGAGTTCGGTGATACCCATGCGGAGCTGCTGTCATATGGTTCCCTCACTTCCTACTAGATGAAAACCGTGGACATACGCAACGTGATCCCCCTGGATAACCCAAACTTAGCGGTCAGCTCCGACGGCGCACCTCAGTTGTATTCTGCGGATAAGTTTCGAAACTACTACCATTGATCCTTGCTGATGACAAGCAGCGTTTTATGATTCATGGTACTGGGGAAGCGAGAGCGTCGACCGGACAATCACACTAAACTTTCGCTGAAAACTAAGACTACCCTTAAGTCCACAGTCTATAGTAGTTAATCACGCTCCTACTAGTCGGCAGGCTTAACAAAGACGTGATCGGGCTGGCTGATGACTCCCAGTCCTCCTGCCAGCTGCGGGACAACGGCCAACATTTCGCAGTTTACTTGGTCCCGCCCGACATCTCGGGATTAAAACCAAACCCAAAAAGTTTTAACCGTCCGGGGCGTCAAGTGTCGGCGTAACAATAGACCAGGTACCCGCGTCACAGTCAAGTTCTTAAGCAATTGACACGTCCCACGTACTTGGATCGCGTTCAAACACGTCGAATGGGTGCTGCGACCGGCAGCATCGAATTATAACAATAAGAGCACAAGATCCCGTGAACCGTTTACGTTGCCTGTGAAAAGGTAGGACGCCGAATTCATGTAGTCGGTATAGTTATATCTTCCGGGAAAATATTATCGCTAAGATCGCATCCCCGAAAGATGTTGATTGGGAGGCACCCCCTACTCATCGCAGAAATCGATCTATTGCTGCTAAAACTAATGATACAGCAGATCCTGGGTTGAGTGCACATCTGGGACTGTATGAGGAATGTGTACCCTCGCCT'
    counter = DNA(input)
    print(*counter.nucleotide_count)

if __name__ == '__main__':
    main()
